import { COMPARE_TYPES } from "../../../../../core/functions/conditions";

export const badgeAttributes = [
  {
    type: "select",
    apiType: "JSON",
    placeholder: "Badge Type",
    collection: "",
    name: "badgeType",
    showItem: "badgeType",
    selectApi: [
      { id: "COMMON_TICKET", value: "Common Ticket" },
      { id: "SPECIFIC_TICKET", value: "Specific Ticket" },
      { id: "COMMON_PARTICIPANT", value: "Common Participant" },
      { id: "SPECIFIC_PARTICIPANT", value: "Specific Participant" },
    ],
    validation: "",
    label: "Badge Type",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: false,
    // selectType: "card",
    statusLabel: {
      nextLine: false,
      size: "small",
      conditions: [
        {
          when: "isActive",
          condition: COMPARE_TYPES.IS_TRUE,
          compare: "true",
          type: "boolean",
          label: "Enabled",
          icon: "tick",
          color: "mint",
        },
        {
          when: "isActive",
          condition: COMPARE_TYPES.IS_FALSE,
          compare: "false",
          type: "boolean",
          label: "Disabled",
          icon: "close",
          color: "beige",
        },
        {
          when: "type",
          condition: COMPARE_TYPES.EQUALS,
          compare: "Default",
          type: "string",
          label: "Participant Type",
          icon: "participant-type",
          color: "mint",
        },
        {
          when: "type",
          condition: COMPARE_TYPES.EQUALS,
          compare: "User-Created",
          type: "string",
          label: "Participant Type",
          icon: "participant-type",
          color: "mint",
        },
      ],
    },
  },
  {
    type: "multiSelect",
    placeholder: "Applicable Tickets",
    name: "tickets",
    validation: "",
    default: "",
    label: "Applicable Tickets",
    tag: true,
    showItem: "value",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "ticket",
    apiType: "API",
    selectApi: "ticket/select/all/Ticket",
    // selectType: "card",
    condition: {
      item: "badgeType",
      if: "SPECIFIC_TICKET",
      then: "enabled",
      else: "disabled",
    },
  },
  {
    type: "multiSelect",
    placeholder: "Applicable Participant Types",
    name: "participantTypes",
    validation: "",
    default: "",
    label: "Applicable Participant Types",
    tag: true,
    showItem: "value",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "participant",
    apiType: "API",
    selectApi: "participant-type/select",
    // selectType: "card",
    condition: {
      item: "badgeType",
      if: "SPECIFIC_PARTICIPANT",
      then: "enabled",
      else: "disabled",
    },
  },
  {
    type: "toggle",
    placeholder: "Enable Badge?",
    name: "isActive",
    validation: "",
    default: true,
    footnote: "This enables the badge to be used in the event",
    label: "Enable Badge",
    tag: false,
    required: true,
    view: true,
    add: false,
    update: true,
  },
];
