export const partnersSpotlightsAttributes = [
  {
    type: "select",
    apiType: "API",
    selectApi: "event/select",
    placeholder: "Event",
    name: "event",
    showItem: "title",
    validation: "",
    default: "",
    tag: false,
    label: "Event",
    required: false,
    view: false,
    add: false,
    update: false,
    filter: false,
    icon: "event",
  },
  {
    type: "text",
    placeholder: "Partner Name",
    name: "partnerName",
    validation: "",
    default: "",
    label: "Partner Name",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "name",
  },
  {
    type: "image",
    placeholder: "Logo",
    name: "logo",
    validation: "",
    default: "",
    label: "Logo",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "image",
  },
  {
    type: "text",
    placeholder: "Link",
    name: "link",
    validation: "",
    default: "",
    label: "Link",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "url",
  },
  {
    type: "number",
    placeholder: "Clicks",
    name: "clicks",
    validation: "",
    default: "",
    label: "Clicks",
    required: false,
    view: true,
    add: false,
    update: false,
    icon: "count",
  },
  {
    type: "number",
    placeholder: "Impressions",
    name: "impressions",
    validation: "",
    default: "",
    label: "Impressions",
    required: false,
    view: true,
    add: false,
    update: false,
    icon: "count",
  },
];
