export const policyAttributes = [
  {
    type: "label",
    label: "Accessibility",
    name: "sm",
    group: "Accessibility",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Accessibility",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Enable Accessibility",
    name: "accessibility",
    validation: "",
    default: true,
    tag: true,
    group: "Accessibility",
    label: "Enable Accessibility",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Whatsapp Floatting",
    name: "sm",
    group: "Whatsapp Floatting",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Whatsapp Floatting",
  },
  {
    type: "toggle",
    placeholder: "Enable Whatsapp Floatting",
    name: "whatsappFloatting",
    validation: "",
    default: false,
    tag: true,
    group: "Whatsapp Floatting",
    label: "Enable Whatsapp Floatting",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Whatsapp Number",
    name: "whatsappNumber",
    condition: {
      item: "whatsappFloatting",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    tag: true,
    group: "Whatsapp Floatting",
    label: "Whatsapp Number",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "AI Voice",
    name: "sm",
    group: "AI Voice",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "AI Voice",
  },
  {
    type: "toggle",
    placeholder: "Enable AI Voice",
    name: "aiVoice",
    validation: "",
    default: true,
    tag: true,
    group: "AI Voice",
    label: "Enable AI Voice",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Cookies",
    name: "sm",
    group: "Cookies",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Cookies",
  },
  {
    type: "toggle",
    placeholder: "Enable Cookies",
    name: "cookie",
    validation: "",
    default: true,
    tag: true,
    group: "Cookies",
    label: "Enable Cookies",
    required: false,
    view: true,
    add: true,
    update: true,
  },
];

export const cookiesAttributes = [
  {
    type: "label",
    label: "Consent and Cookies",
    name: "sm",
    group: "Consent and Cookies",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Consent and Cookies",
  },
  {
    type: "toggle",
    placeholder: "Enable Cookies Banner",
    name: "cookieBanner",
    validation: "",
    default: true,
    tag: true,
    group: "Consent and Cookies",
    label: "Enable Cookies Banner",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Policy",
    name: "cookiesPolicy",
    validation: "",
    default: true,
    tag: true,
    group: "Consent and Cookies",
    label: "Policy",
    condition: {
      item: "cookieBanner",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Policies",
    name: "sm",
    group: "Policies",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Policies",
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Privacy Policy",
    name: "privacyPolicy",
    validation: "",
    default: true,
    tag: true,
    group: "Policies",
    label: "Privacy Policy",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Terms and Condition",
    name: "termsAndCondition",
    validation: "",
    default: true,
    tag: true,
    group: "Policies",
    label: "Terms and Condition",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Cancelation and Refund Policy",
    name: "cancelationAndRefundPolicy",
    validation: "",
    default: true,
    tag: true,
    group: "Policies",
    label: "Cancelation and Refund Policy",
    required: false,
    view: true,
    add: true,
    update: true,
  },
];
