import { getCountries } from "../countries";

export const exhibitorAttributes = (eventCountries = []) => {
  return [
    {
      type: "select",
      apiType: "API",
      selectApi: "event/select",
      placeholder: "Event",
      name: "event",
      showItem: "title",
      validation: "",
      default: "",
      tag: false,
      label: "Event",
      required: false,
      view: false,
      add: false,
      update: false,
      filter: false,
      icon: "event",
    },
    {
      type: "text",
      placeholder: "Company Name",
      name: "firstName",
      validation: "",
      default: "",
      label: "Company Name",
      required: true,
      tag: true,
      view: true,
      add: true,
      update: true,
      icon: "company",
      image: { type: "image", field: "logo", collection: "" },
      description: { type: "email", field: "emailId", collection: "" },
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "exhibitor-category/select",
      placeholder: "Exhibitor Category",
      name: "exhibitorCategory",
      validation: "",
      showItem: "categoryName",
      collection: "exhibitorCategory",
      addNew: {
        attributes: [
          {
            type: "text",
            placeholder: "Category Name",
            name: "categoryName",
            validation: "",
            default: "",
            label: "Add an exhibitor category",
            required: true,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "select",
            placeholder: "Price",
            // listView: true,
            // radioButton: true,
            name: "freeOrPaid",
            validation: "",
            default: "Free",
            label: "Price",
            tag: true,
            required: true,
            view: true,
            customClass: "full",
            add: true,
            update: true,
            apiType: "JSON",
            selectType: "card",
            search: false,
            selectApi: [
              { value: "Free", id: "Free" },
              { value: "Paid", id: "Paid" },
            ],
          },
          {
            type: "number",
            placeholder: "Amount",
            name: "price",
            condition: {
              item: "freeOrPaid",
              if: "Paid",
              then: "enabled",
              else: "disabled",
            },
            validation: "",
            tag: true,
            label: "Amount",
            // showItem: "value",
            required: false,
            view: true,
            filter: false,
            add: true,
            update: true,
          },
          {
            type: "toggle",
            placeholder: "Lead Capture",
            name: "leadCapture",
            validation: "",
            default: true,
            label: "Lead Capture",
            tag: true,
            required: false,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "number",
            placeholder: "Passes",
            name: "exhibitorPasses",
            validation: "",
            default: "",
            tag: true,
            label: "Passes",
            required: true,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "textarea",
            placeholder: "Description",
            name: "description",
            validation: "",
            default: "",
            label: "Description",
            required: false,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "toggle",
            placeholder: "Is Active",
            name: "isActive",
            validation: "",
            default: "",
            tag: true,
            label: "Is Active",
            required: false,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "htmleditor",
            placeholder: "Booth Details & Benefits",
            name: "boothDetails",
            validation: "",
            default: "",
            tag: true,
            label: "Details about the booth",
            sublabel: "Optional",
            required: false,
            view: true,
            add: true,
            update: true,
            footnote: "Can include details like Booth Dimensions, etc",
            footnoteIcon: "info",
          },
        ],
        api: "exhibitor-category",
        submitButtonText: "Create",
      },
      default: "",
      tag: true,
      label: "Exhibitor Category",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
      search: true,
    },
    {
      type: "number",
      placeholder: "Booth Number",
      name: "boothNumber",
      validation: "",
      default: "",
      label: "Booth Number",
      icon: "location",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Website",
      name: "website",
      validation: "",
      default: "",
      label: "Website",
      icon: "url",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "Logo",
      name: "logo",
      validation: "",
      default: "",
      label: "Logo",
      icon: "image",
      required: false,
      view: true,
      add: true,
      update: true,
      sublabel: "Image to display in exhibitor listings",
    },
    {
      type: "mobilenumber",
      placeholder: "Mobile",
      name: "authenticationId",
      validation: "",
      default: "",
      label: "Admin Mobile Number",
      icon: "mobilenumber",
      required: true,
      view: true,
      add: true,
      update: true,
      search: true,
      footnote: "This mobile number will be used as the login credential for the exhibitor's mobile app",
      countries: getCountries(eventCountries),
    },
    {
      type: "email",
      placeholder: "Email",
      name: "emailId",
      validation: "",
      default: "",
      tag: true,
      label: "Email",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "textarea",
      placeholder: "Description",
      name: "bio",
      validation: "",
      default: "",
      label: "Description",
      icon: "description",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ];
};

export const boothMemberAttributes = (eventCountries = []) => {
  return [
    {
      type: "select",
      apiType: "API",
      selectApi: "ticket-registration/exhibitor/select",
      name: "parentExhibitor",
      showItem: "firstName",
      label: "Exhibitor",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
      search: true,
      icon: "exhibitor",
    },
    {
      type: "text",
      placeholder: "Name",
      name: "fullName",
      validation: "",
      default: "",
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
      tag: true,
      icon: "name",
    },
    {
      type: "text",
      placeholder: "Designation",
      name: "designation",
      validation: "",
      default: "",
      label: "Designation",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
      icon: "user-group",
    },
    {
      type: "email",
      placeholder: "Email",
      name: "emailId",
      validation: "",
      default: "",
      label: "Email",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
      icon: "email",
    },
    {
      type: "mobilenumber",
      placeholder: "Mobile",
      name: "authenticationId",
      validation: "",
      default: "",
      label: "Mobile",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
      icon: "mobilenumber",
      countries: getCountries(eventCountries),
    },
  ];
};

export const exhibitorCategoryAttributes = [
  {
    type: "text",
    placeholder: "Enter Category Name",
    name: "categoryName",
    validation: "",
    default: "",
    label: "Category Name",
    required: true,
    view: true,
    add: true,
    tag: true,
    update: true,
    icon: "exhibitor-category",
  },
  {
    type: "select",
    placeholder: "Price",
    name: "freeOrPaid",
    validation: "",
    default: "Free",
    label: "Price",
    tag: true,
    required: true,
    view: true,
    customClass: "full",
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    search: false,
    selectApi: [
      { value: "Free", id: "Free" },
      { value: "Paid", id: "Paid" },
    ],
    icon: "price",
  },
  {
    type: "number",
    placeholder: "Amount",
    name: "price",
    condition: {
      item: "freeOrPaid",
      if: "Paid",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    tag: true,
    label: "Amount",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
    icon: "currency",
  },
  {
    type: "toggle",
    placeholder: "Lead Capture",
    name: "leadCapture",
    validation: "",
    default: true,
    label: "Lead Capture",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "qr-code",
  },
  {
    type: "number",
    placeholder: "Passes",
    name: "exhibitorPasses",
    validation: "",
    default: "",
    tag: true,
    label: "Passes",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "badge",
  },
  {
    type: "toggle",
    placeholder: "Is Active",
    name: "isActive",
    validation: "",
    default: "",
    tag: true,
    label: "Is Active",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "configure",
  },
  {
    type: "htmleditor",
    placeholder: "Description",
    name: "description",
    validation: "",
    default: "",
    label: "Description",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "description",
  },
  {
    type: "htmleditor",
    placeholder: "Booth Details & Benefits",
    name: "boothDetails",
    validation: "",
    default: "",
    tag: true,
    label: "Details about the booth",
    sublabel: "Optional",
    required: false,
    view: true,
    add: true,
    update: true,
    footnote: "Can include details like Booth Dimensions, etc",
    footnoteIcon: "info",
    icon: "description",
  },
];

export const downloadAttributes = [
  {
    type: "text",
    placeholder: "Title",
    name: "title",
    validation: "",
    default: "",
    label: "Title",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Description",
    name: "description",
    validation: "",
    default: "",
    label: "Description",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "file",
    placeholder: "Attachment",
    name: "attachment",
    validation: "",
    default: "",
    label: "Attachment",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
  },
];

export const floorPlanAttributes = [
  {
    type: "text",
    placeholder: "Title",
    name: "title",
    validation: "",
    default: "",
    label: "Title",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "file",
    placeholder: "Attachment",
    name: "attachment",
    validation: "",
    default: "",
    label: "Attachment",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
  },
];

export const faqAttributes = [
  {
    type: "text",
    placeholder: "Question",
    name: "question",
    validation: "",
    default: "",
    label: "Question",
    required: true,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "htmleditor",
    placeholder: "Answer",
    name: "answer",
    validation: "",
    default: "",
    label: "Answer",
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Type",
    name: "type",
    validation: "",
    default: "",
    label: "Type",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
  },
];

export const exhibitorFormAttributes = [
  {
    type: "text",
    placeholder: "Company Name",
    name: "companyName",
    validation: "",
    default: "",
    label: "Company Name",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "company",
  },
  {
    type: "text",
    placeholder: "Email",
    name: "email",
    validation: "",
    default: "",
    label: "Email",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "email",
  },
  {
    type: "text",
    placeholder: "Mobile Number",
    name: "mobileNumber",
    validation: "",
    default: "",
    label: "Mobile Number",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "mobilenumber",
  },
  {
    type: "text",
    placeholder: "Designation",
    name: "designation",
    validation: "",
    default: "",
    label: "Designation",
    required: true,
  },
  {
    type: "select",
    placeholder: "Country",
    name: "country",
    validation: "",
    default: "",
    label: "Country",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "location",
    apiType: "API",
    selectApi: "country/select",
    showItem: "countryName",
    search: true,
    tag: true,
    required: true,
    view: true,
  },
  {
    type: "select",
    placeholder: "Exhibitor Category",
    name: "exhibitorCategory",
    validation: "",
    default: "",
    label: "Exhibitor Category",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "exhibitor-category",
    apiType: "API",
    selectApi: "exhibitor-category/select",
    showItem: "categoryName",
    search: true,
    tag: true,
    required: true,
    view: true,
  },
  {
    type: "htmleditor",
    placeholder: "Description",
    name: "description",
    validation: "",
    default: "",
    label: "Description",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "description",
  },
];

export const passesAttributes = [
  {
    type: "number",
    placeholder: "Number of Passes",
    name: "numberOfPasses",
    validation: "",
    default: "",
    label: "Number of Passes",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "badge",
  },
  {
    type: "select",
    placeholder: "Exhibitor Category",
    name: "exhibitorCategory",
    validation: "",
    default: "",
    label: "Exhibitor Category",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "exhibitor-category",
    apiType: "API",
    selectApi: "exhibitor-category/select",
    showItem: "value",
    search: true,
    tag: true,
    required: true,
    view: true,
  },
  {
    type: "select",
    placeholder: "Ticket",
    name: "ticket",
    validation: "",
    default: "",
    label: "Ticket",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "ticket",
    apiType: "API",
    selectApi: "ticket/event-ticket",
    showItem: "value",
    search: true,
    tag: true,
    required: false,
    view: true,
  },
];
