import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const OrganisationSetting = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Organization - goCampus Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "title",
      title: "Basic Configurations",
      name: "Basic Configurations",
      icon: "configuration",
      add: false,
      update: true,
      info: "Configure the basic details of your organisation",
    },
    {
      type: "text",
      placeholder: "Organisation Name",
      name: "name",
      validation: "",
      default: "",
      label: "Organisation Name",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
      customClass: "full",
    },
    {
      type: "textarea",
      placeholder: "Address",
      name: "address",
      validation: "",
      default: "",
      tag: true,
      label: "Address",
      required: true,
      view: true,
      add: true,
      update: true,
      customClass: "full",
    },
    {
      type: "title",
      title: "Primary Contact",
      name: "primaryContact",
      icon: "call",
      add: false,
      update: true,
    },
    {
      type: "text",
      placeholder: "Email",
      name: "email",
      validation: "",
      default: "",
      label: "Email",
      tag: false,
      required: true,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Phone",
      name: "phone",
      validation: "",
      default: "",
      tag: true,
      label: "Phone",
      required: true,
      view: true,
      add: true,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Website",
      name: "website",
      validation: "",
      default: "",
      tag: true,
      label: "Website",
      required: false,
      view: true,
      add: true,
      update: true,
      customClass: "half",
    },
    {
      type: "title",
      title: "Other Informations",
      name: "Other Informations",
      icon: "info",
      add: false,
      update: true,
    },
    {
      type: "image",
      placeholder: "Logo",
      name: "logo",
      validation: "",
      default: "false",
      tag: true,
      label: "Organisation Logo",
      footnote: "For best results, use a logo with a transparent background",
      required: false,
      view: true,
      add: true,
      update: true,
      customClass: "half",
    },
    {
      type: "image",
      placeholder: "Banner",
      name: "banner",
      validation: "",
      default: "false",
      tag: true,
      label: "Organisation Banner",
      footnote: "For best results, use a 850*350px landscape image",
      required: false,
      view: true,
      add: true,
      update: true,
      customClass: "half",
    },
    {
      type: "line",
      add: false,
      update: true,
    },
    {
      type: "htmleditor",
      placeholder: "About Your Organisation",
      // placeholder: "Give attendees an overview of your event—what to expect, who should attend, and any special highlights",
      name: "description",
      validation: "",
      default: "",
      label: "About Your Organisation",
      tag: false,
      required: false,
      view: false,
      add: false,
      update: true,
    },
    {
      type: "title",
      title: "Social Media Links",
      icon: "link",
      name: "sm",
      add: false,
      update: true,
    },
    {
      type: "toggle",
      placeholder: "Enable Social Media?",
      name: "enableSocialMedia",
      validation: "",
      default: "",
      label: "Enable Social Media?",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      footnote: "Add organisation's social media profiles",
      customClass: "full",
    },

    {
      type: "text",
      placeholder: "Link your organisation's Facebook page",
      name: "facebook",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Facebook URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's Instagram page",
      name: "insta",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Instagram URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's X page",
      name: "xSocial",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "X URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's LinkedIn page",
      name: "linkedin",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Linkedin URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's Youtube channel",
      name: "youtube",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Youtube URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's Whatsapp number",
      name: "whatsapp",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Whatsapp URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
    {
      type: "text",
      placeholder: "Link your organisation's Threads page",
      name: "threads",
      condition: {
        item: "enableSocialMedia",
        if: true,
        then: "enabled",
        else: "disabled",
      },
      validation: "",
      default: "",
      label: "Threads URL",
      tag: false,
      required: false,
      view: true,
      add: false,
      update: true,
      customClass: "half",
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`franchise`}
        itemTitle={{ name: "name", type: "text", collection: "" }}
        shortName={`Organization`}
        showTitle={false}
        formMode={`single`}
        attributes={attributes}
        addPrivilege={false}
        viewMode={"info"}
        {...props}
      ></ListTable>
    </Container>
  );
};

export default Layout(OrganisationSetting);
