export const photoPermissionAttributes = [
  {
    type: "label",
    label: "Photo View Access",
    info: "Select who want to view photos",
    name: "sm",
    group: "Photo Viewing Access",
    icon: "photo-view-access",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Photo Viewing Access",
    icon: "photo-view-access",
    add: true,
    update: true,
  },
  // {
  //   type: "select",
  //   apiType: "CSV",
  //   placeholder: "Photo View Access",
  //   name: "photoViewAccess",
  //   selectApi: "Attendees,Everyone",
  //   validation: "",
  //   default: "",
  //   label: "Photo View Access",
  //   group: "Photo Viewing Access",
  //   tag: true,
  //   required: false,
  //   view: true,
  //   add: true,
  //   update: true,
  // },
  {
    type: "select",
    placeholder: "Photo View Access",
    name: "photoViewAccess",
    validation: "",
    editable: true,
    label: "Photo View Access",
    customClass: "full",
    showItem: "",
    required: true,
    filter: false,
    view: true,
    add: true,
    group: "Photo Viewing Access",
    update: true,
    apiType: "JSON",
    selectType: "card",
    info: "Based on your selection permission will be allowed.",
    selectApi: [
      {
        value: "Attendees",
        id: "Attendees",
        description: "Only registered user",
      },
      {
        value: "Everyone",
        id: "Everyone",
        description: "Anyone can login to this",
      },
    ],
    default: "Everyone",
  },
  {
    type: "label",
    label: "Event Highlights",
    info: "Manage your event highlights",
    name: "sm",
    group: "Event Highlights",
    icon: "event-highlights",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Event Highlights",
    icon: "event-highlights",
  },
  {
    type: "toggle",
    placeholder: "Event Highlights",
    name: "enableEventHighlights",
    validation: "",
    default: true,
    group: "Event Highlights",
    label: "Event Highlights",
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Social Share",
    info: "Manage your social media connections",
    name: "sm",
    group: "Social Share",
    icon: "social-share",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Social Share",
    icon: "social-share",
  },
  {
    type: "toggle",
    placeholder: "Social Share",
    name: "enableSocialShare",
    validation: "",
    default: true,
    tag: true,
    group: "Social Share",
    label: "Social Share",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Social Share Content",
    name: "socialShareContent",
    condition: {
      item: "enableSocialShare",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: true,
    tag: true,
    group: "Social Share",
    label: "Social Share Content",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Partner Spotlights",
    info: "Add you partner ads",
    name: "sm",
    group: "Display Ads",
    icon: "display",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Display Ads",
    icon: "display",
  },
  {
    type: "toggle",
    placeholder: "Partner Spotlights",
    name: "enablePartnerSpotlights",
    validation: "",
    default: true,
    tag: true,
    group: "Display Ads",
    label: "Partner Spotlights",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Whatsapp Auth",
    info: "Manage your whatsapp authentications",
    name: "sm",
    group: "Whatsapp Authentications",
    icon: "whatsapp-auth",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Whatsapp Authentications",
    icon: "whatsapp-auth",
  },
  {
    type: "toggle",
    placeholder: "Whatsapp Auth",
    name: "isWhatsappAuth",
    validation: "",
    default: true,
    tag: true,
    group: "Whatsapp Authentications",
    label: "Whatsapp Auth",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Profile Fields",
    info: "Manage your profile fields",
    name: "sm",
    group: "Profile Fields",
    icon: "profile-fields",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Profile Fields",
    icon: "profile-fields",
  },
  {
    type: "toggle",
    placeholder: "Name",
    name: "name",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Name",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Whatsapp Number",
    name: "whatsappNumber",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Whatsapp Number",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Mobile Number",
    name: "mobileNumber",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Mobile Number",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Designation",
    name: "designation",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Designation",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Company",
    name: "company",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Company",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Gender",
    name: "gender",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Gender",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Bio",
    name: "bio",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Bio",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
];
