import { COMPARE_TYPES } from "../../../../../core/functions/conditions";

export const instanceAttributes = [
  {
    type: "text",
    placeholder: "Instance Name",
    name: "title",
    validation: "",
    default: "",
    label: "Instance Name",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "text",
  },
  {
    type: "select",
    placeholder: "Applicable Tickets",
    name: "ticketType",
    validation: "",
    tag: false,
    editable: true,
    default: "All Tickets",
    label: "Who Can Attend?",
    sublabel: "",
    showItem: "",
    required: false,
    customClass: "full",
    filter: false,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      { value: "All Tickets", id: 0, description: "Everyone with any ticket type can join" },
      { value: "Selected Tickets & Participant types", id: 1, description: "Limit access to specific ticket types only" },
    ],
    icon: "user-group",
  },
  {
    type: "multiSelect",
    apiType: "API",
    selectApi: "ticket/event-ticket",
    placeholder: "Choose Ticket",
    name: "ticket",
    label: "Selected Ticket",
    updateOn: "event",
    showItem: "title",
    validation: "",
    condition: {
      item: "ticketType",
      if: 1,
      then: "enabled",
      else: "disabled",
    },
    tag: false,
    required: false,
    view: false,
    add: true,
    update: true,
    filter: true,
    export: false,
    footnote: "",
    icon: "ticket",
  },
  {
    type: "multiSelect",
    apiType: "API",
    selectApi: "ticket/event-ticket",
    placeholder: "Choose Ticket",
    name: "ticket",
    label: "Select Ticket",
    updateOn: "event",
    showItem: "title",
    validation: "",
    tag: true,
    required: false,
    view: true,
    add: false,
    update: false,
    filter: false,
    export: false,
    footnote: "",
    icon: "ticket",
  },
];

export const instanceDataAttributes = [
  {
    type: "select",
    name: "type",
    label: "Type",
    apiType: "JSON",
    filterType: "tabs",
    filter: true,
    filterPosition: "right",
    value: "all",
    filterDefault: "all",
    selectApi: [
      {
        id: "all",
        value: "All",
      },
      {
        id: "check-in",
        value: "Check-in",
      },
      {
        id: "pending-list",
        value: "Pending",
      },
    ],
  },
  {
    type: "text",
    placeholder: "Name",
    name: "firstName",
    collection: "user",
    validation: "",
    default: "",
    tag: true,
    label: "Name",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "mobilenumber",
    placeholder: "Phone Number",
    name: "authenticationId",
    collection: "user",
    validation: "",
    default: "",
    tag: true,
    label: "Phone Number",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "email",
    placeholder: "Email ID",
    name: "emailId",
    validation: "",
    collection: "user",
    default: "",
    tag: true,
    label: "Email ID",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "datetime",
    placeholder: "Checkin Time",
    name: "createdAt",
    validation: "",
    collection: "attendance",
    showItem: "createdAt",
    default: "",
    tag: false,
    label: "Checkin Time",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "hidden",
    placeholder: "Status",
    name: "status",
    validation: "",
    default: "",
    tag: true,
    label: "Status",
    required: true,
    view: true,
    add: false,
    update: false,
    hide: true,
    statusLabel: {
      nextLine: false,
      size: "small",
      conditions: [
        {
          when: "hasAttended",
          condition: COMPARE_TYPES.IS_TRUE,
          compare: true,
          type: "boolean",
          label: "Checked In",
          icon: "checked",
          color: "mint",
        },
        {
          when: "hasAttended",
          condition: COMPARE_TYPES.IS_FALSE,
          compare: false,
          type: "boolean",
          label: "Pending",
          icon: "pending",
          color: "beige",
        },
      ],
    },
  },
];

// export const instanceActionsAttributes = [
//   {
//     element: "button",
//     type: "callback",
//     callback: (item, data, refreshView, slNo) => {
//       // getApproved(data._id, refreshView, slNo, "approve");
//     },
//     itemTitle: {
//       name: "user",
//       type: "text",
//       collection: "",
//     },
//     condition: {
//       item: "instance",
//       if: false,
//       then: true,
//       else: false,
//     },
//     icon: "checked",
//     color: "green",
//     title: "Check In",
//     params: {
//       api: ``,
//       parentReference: "",
//       itemTitle: {
//         name: "user",
//         type: "text",
//         collection: "",
//       },
//       shortName: "Check In",
//       addPrivilege: true,
//       delPrivilege: true,
//       updatePrivilege: true,
//       customClass: "medium",
//     },
//   },
// ];
