export const paymentHistoryAttributes = [
  {
    type: "text",
    placeholder: "User",
    name: "authentication",
    collection: "authentication",
    showItem: "fullName",
    tag: true,
    label: "User",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "user",
    sort: true,
  },
  {
    type: "text",
    placeholder: "Mobile",
    name: "authentication",
    collection: "authentication",
    showItem: "authenticationId",
    tag: true,
    label: "Mobile",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "mobilenumber",
    sort: true,
  },
  {
    type: "text",
    placeholder: "Ticket",
    name: "ticket",
    collection: "ticket",
    showItem: "title",
    tag: true,
    label: "Ticket",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "ticket",
    sort: true,
  },
  {
    type: "hidden",
    placeholder: "Event",
    name: "event",
    collection: "event",
    showItem: "title",
    tag: false,
    label: "Event",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "event",
  },
  {
    type: "text",
    placeholder: "Razorpay Payment Id",
    name: "razorpayPaymentId",
    tag: false,
    label: "Razorpay Payment Id",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "payment",
    sort: true,
  },
  {
    type: "text",
    placeholder: "Currency",
    name: "currency",
    tag: true,
    label: "Currency",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "currency",
  },
  {
    type: "text",
    placeholder: "Quantity",
    name: "cartSummary",
    collection: "cartSummary",
    showItem: "quantity",
    tag: true,
    label: "Quantity",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "quantity",
    render: (value, data, attribute) => {
      const cartSummary = data.cartSummary;
      if (Array.isArray(cartSummary) && cartSummary.length > 0) {
        const totalQuantity = cartSummary.reduce((sum, item) => sum + (item.quantity || 0), 0);
        return totalQuantity.toString();
      }
      return "0";
    },
  },
  {
    type: "number",
    placeholder: "Unit Price",
    name: "cartSummary",
    collection: "cartSummary",
    showItem: "unitPrice",
    tag: true,
    label: "Unit Price",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "price",
    render: (value, data, attribute) => {
      const cartSummary = data.cartSummary;
      if (Array.isArray(cartSummary) && cartSummary.length > 0) {
        return cartSummary[0].unitPrice?.toString() || "0";
      }
      return "0";
    },
  },
  {
    type: "number",
    placeholder: "Discount Amount",
    name: "discountAmount",
    tag: true,
    label: "Discount Amount",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "discount",
  },
  {
    type: "number",
    placeholder: "Total Amount",
    name: "amount",
    tag: true,
    label: "Total Amount",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "price",
  },
  {
    type: "text",
    placeholder: "Status",
    name: "status",
    tag: true,
    label: "Status",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "status",
  },
];
