import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const BillingAddress = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Billing Address - goCampus Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "select",
      apiType: "API",
      selectApi: "franchise/select",
      placeholder: "Franchise",
      name: "franchise",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Franchise",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "title",
      title: "Address Details",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Address Line 1",
      name: "addressLine1",
      validation: "",
      default: "",
      tag: false,
      label: "Address Line 1",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Address Line 2",
      name: "addressLine2",
      validation: "",
      default: "",
      tag: false,
      label: "Address Line 2",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "City",
      name: "city",
      validation: "",
      default: "",
      tag: false,
      label: "City",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "State",
      name: "state",
      validation: "",
      default: "",
      tag: false,
      label: "State",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Country",
      name: "country",
      validation: "",
      default: "",
      tag: false,
      label: "Country",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Postal Code",
      name: "postalCode",
      validation: "",
      default: "",
      tag: false,
      label: "Postal Code",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      title: "Billing Contact Information",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "First Name",
      name: "contactPersonfirstName",
      validation: "",
      default: "",
      tag: false,
      label: "First Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Last Name",
      name: "contactPersonlastName",
      validation: "",
      default: "",
      tag: false,
      label: "Last Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Email",
      name: "contactPersonemail",
      validation: "",
      default: "",
      tag: true,
      label: "Email",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Phone",
      name: "contactPersonphone",
      validation: "",
      default: "",
      tag: true,
      label: "Phone",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Designation",
      name: "contactPersondesignation",
      validation: "",
      default: "",
      tag: true,
      label: "Designation",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      title: "Billing Details",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Company Name",
      name: "companyName",
      validation: "",
      default: "",
      tag: true,
      label: "Company Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Tax ID",
      name: "taxId",
      validation: "trim",
      default: "",
      tag: true,
      label: "Tax ID",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "VAT Number",
      name: "vatNumber",
      validation: "trim",
      default: "",
      tag: true,
      label: "VAT Number",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "GST Number",
      name: "gstNumber",
      validation: "trim",
      default: "",
      tag: true,
      label: "GST Number",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "toggle",
      placeholder: "Is Default",
      name: "isDefault",
      validation: "",
      default: false,
      tag: true,
      label: "Is Default",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`billing-address`}
        itemTitle={{ name: "contactPersonfirstName", type: "text", collection: "" }}
        shortName={`Billing Address`}
        // parentReference={"event"}
        formMode={`double`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
// exporting the page with parent container layout..
export default Layout(BillingAddress);
