export const speakersAttributes = [
  {
    type: "text",
    placeholder: "Enter Speaker Name",
    name: "name",
    validation: "",
    default: "",
    label: "Speaker Name",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
    image: { field: "photo", collection: "" },
    description: { type: "text", field: "email", collection: "" },
    icon: "speakers",
  },
  {
    type: "select",
    apiType: "API",
    selectApi: "anchor/master/select",
    placeholder: "Select Role Type",
    name: "anchor",
    validation: "",
    showItem: "anchor",
    default: "",
    tag: true,
    addNew: {
      attributes: [
        {
          type: "text",
          placeholder: "Enter Speaker Role",
          name: "anchor",
          validation: "",
          default: "",
          label: "Add a speaker role",
          required: true,
          view: true,
          add: true,
          update: true,
          icon: "speakers",
        },
      ],
      api: "anchor",
      submitButtonText: "Create",
    },
    highlight: true,
    label: "Speaker Role",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: true,
    icon: "speakers",
  },
  {
    type: "text",
    placeholder: "Job Title or Role",
    name: "designation",
    validation: "",
    default: "",
    label: "Designation",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "location",
  },
  {
    type: "text",
    placeholder: "Organization or Affiliation",
    name: "company",
    validation: "",
    default: "",
    label: "Company",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "company",
  },
  {
    type: "text",
    placeholder: "Enter Email",
    name: "email",
    validation: "",
    default: "",
    label: "Email",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "email",
  },
  {
    type: "number",
    placeholder: "Order Number",
    name: "orderId",
    validation: "",
    default: "",
    label: "Order Number",
    required: false,
    view: true,
    add: true,
    update: true,
    footnote: "Display position on website(1 appears first)",
    icon: "orders",
  },
  {
    type: "image",
    placeholder: "Image",
    name: "photo",
    validation: "",
    default: "false",
    tag: false,
    label: "Profile Picture",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Enter speaker bio and relevant experience...",
    name: "description",
    validation: "",
    default: "",
    label: "Speaker Bio",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "email",
  },
  {
    type: "title",
    title: "Social Media Configuration",
    name: "sm",
    add: true,
    update: true,
    info: "Add speaker's social media profiles for attendees to connect",
  },
  {
    type: "toggle",
    placeholder: "Enable Social Media?",
    name: "enableSocialMedia",
    validation: "",
    default: "",
    label: "Enable Social Media?",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    footnote: "Add speaker's social media profiles",
  },
  {
    type: "text",
    placeholder: "Link your event's email",
    name: "email",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Email",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's Facebook page",
    name: "facebook",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Facebook URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's Instagram page",
    name: "insta",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Instagram URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's X page",
    name: "xSocial",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "X URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's LinkedIn page",
    name: "linkedin",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Linkedin URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's Youtube channel",
    name: "youtube",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Youtube URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's Whatsapp number",
    name: "whatsapp",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Whatsapp URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "text",
    placeholder: "Link your event's Threads page",
    name: "threads",
    condition: {
      item: "enableSocialMedia",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Threads URL",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
    customClass: "half",
  },
  {
    type: "datetime",
    placeholder: "Created At",
    name: "createdAt",
    validation: "",
    default: "",
    label: "Created At",
    tag: false,
    required: false,
    view: true,
    add: false,
    update: false,
  },
];
