export const advocacyPosterUsageAttributes = [
  {
    type: "text",
    placeholder: "Reference",
    name: "reference",
    validation: "",
    label: "Reference",
    required: true,
    view: true,
    tag: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Image Builder Data",
    name: "imageBulderData",
    validation: "",
    label: "Image Builder Data",
    required: true,
    view: true,
    add: true,
    update: true,
    tag: true,
  },
  {
    type: "text",
    placeholder: "Count",
    name: "count",
    validation: "",
    label: "Count",
    required: true,
    view: true,
    add: true,
    update: true,
    tag: true,
  },
  {
    type: "text",
    placeholder: "Date",
    name: "date",
    validation: "",
    label: "Date",
    required: true,
    view: true,
    add: true,
    update: true,
  },
];

// export const mobileModulesAttributes = [
//   {
//     type: "multiSelect",
//     placeholder: "Mobile Modules",
//     name: "mobileModules",
//     validation: "",
//     tag: true,
//     editable: true,
//     label: "",
//     group: "Mobile Module",
//     sublabel: "",
//     showItem: "",
//     required: false,
//     customClass: "full",
//     filter: false,
//     view: true,
//     add: true,
//     update: true,
//     apiType: "JSON",
//     selectType: "card",
//     selectApi: [
//       { value: "InstaSnap", id: "InstaSnap" },
//       { value: "Networking", id: "Networking" },
//       { value: "Meetings", id: "Meetings" },
//       { value: "Messaging", id: "Messaging" },
//       { value: "Speakers", id: "Speakers" },
//       { value: "Exhibitors", id: "Exhibitors" },
//       { value: "Sessions", id: "Sessions" },
//       { value: "Sponsors", id: "Sponsors" },
//       { value: "Feedback", id: "Feedback" },
//       { value: "Videos", id: "Videos" },
//       { value: "Ticket", id: "Ticket" },
//       { value: "AI Chat", id: "AI Chat" },
//     ],
//   },
// ];

// export const appVersionAttributes = [
//   {
//     type: "text",
//     placeholder: "Version",
//     name: "version",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Version",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   // {
//   //   type: "text",
//   //   placeholder: "Link",
//   //   name: "link",
//   //   validation: "",
//   //   default: "",
//   //   label: "Link",
//   //   required: false,
//   //   view: true,
//   //   add: true,
//   //   update: true,
//   // },
// ];

// export const instaSnapAttributes = [
//   {
//     type: "text",
//     placeholder: "Title",
//     name: "title",
//     validation: "",
//     default: "",
//     label: "Title",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     icon: "text",
//   },
// ];

// export const eventHighlightsAttributes = [
//   {
//     type: "select",
//     apiType: "API",
//     selectApi: "event/select",
//     placeholder: "Event",
//     name: "event",
//     showItem: "title",
//     validation: "",
//     default: "",
//     tag: false,
//     label: "Event",
//     required: false,
//     view: false,
//     add: false,
//     update: false,
//     filter: false,
//     icon: "event",
//   },
//   {
//     type: "text",
//     placeholder: "Title",
//     name: "title",
//     validation: "",
//     default: "",
//     label: "Title",
//     tag: true,
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "image",
//     placeholder: "Image",
//     name: "image",
//     validation: "",
//     default: "",
//     label: "Image",
//     tag: true,
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
// ];

// export const uploadHistoryAttributes = [
//   {
//     type: "date",
//     placeholder: "Date",
//     name: "date",
//     validation: "",
//     default: "",
//     label: "Date",
//     tag: true,
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     icon: "date",
//   },
//   {
//     type: "number",
//     placeholder: "Original Size",
//     name: "originalSize",
//     validation: "",
//     default: "",
//     label: "Original Size",
//     tag: true,
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "number",
//     placeholder: "Compressed Size",
//     name: "compressedSize",
//     validation: "",
//     default: "",
//     label: "Compressed Size",
//     tag: true,
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "number",
//     placeholder: "Image Count",
//     name: "imageCount",
//     validation: "",
//     default: "",
//     label: "Image Count",
//     tag: true,
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//   },
// ];

// export const dashboardBannerAttributes = [
//   {
//     type: "text",
//     placeholder: "Image",
//     name: "image",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Image",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//   },
// ];

// export const notificationAttributes = [
//   {
//     type: "text",
//     placeholder: "Title",
//     name: "title",
//     validation: "",
//     default: "",
//     label: "Title",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     icon: "text",
//   },
//   {
//     type: "textarea",
//     placeholder: "Description",
//     name: "description",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Description",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     icon: "description",
//   },
//   {
//     type: "image",
//     placeholder: "Image",
//     name: "image",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Image",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     icon: "image",
//   },
// ];

// export const feedbackAttributes = [
//   {
//     type: "select",
//     apiType: "API",
//     selectApi: "event/select",
//     placeholder: "Event",
//     name: "event",
//     validation: "",
//     showItem: "value",
//     default: "",
//     tag: false,
//     label: "Event",
//     required: false,
//     view: false,
//     add: false,
//     update: false,
//     filter: false,
//   },
//   {
//     type: "select",
//     apiType: "API",
//     selectApi: "ticket-registration/select",
//     placeholder: "User",
//     name: "user",
//     validation: "",
//     showItem: "fullName",
//     default: "",
//     tag: true,
//     label: "User",
//     required: false,
//     view: true,
//     add: false,
//     update: false,
//     filter: false,
//   },
//   {
//     type: "text",
//     placeholder: "Overall",
//     name: "overall",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Overall",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Sessions",
//     name: "sessions",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Sessions",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Content",
//     name: "content",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Content",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
// ];

// export const campaignAttributes = [
//   {
//     type: "text",
//     placeholder: "Campaign Name",
//     name: "campaignName",
//     validation: "",
//     default: "",
//     tag: false,
//     label: "Campaign Name",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "select",
//     apiType: "API",
//     selectApi: "event/select",
//     placeholder: "Audience",
//     name: "audience",
//     validation: "",
//     showItem: "title",
//     default: "",
//     tag: true,
//     label: "Audience",
//     required: true,
//     view: true,
//     add: true,
//     update: true,
//     filter: true,
//   },
//   {
//     type: "text",
//     placeholder: "Campaign Color",
//     name: "campaignColor",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Campaign Color",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "date",
//     placeholder: "Start Date",
//     name: "startDate",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Start Date",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "date",
//     placeholder: "End Date",
//     name: "endDate",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "End Date",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Campaign Goal",
//     name: "goal",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Campaign Goal",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "textarea",
//     placeholder: "Description",
//     name: "description",
//     validation: "",
//     default: "",
//     tag: true,
//     label: "Description",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "select",
//     apiType: "API",
//     selectApi: "event/select",
//     placeholder: "Event",
//     name: "event",
//     validation: "",
//     showItem: "value",
//     default: "",
//     tag: false,
//     label: "Event",
//     required: false,
//     view: false,
//     add: false,
//     update: false,
//     filter: false,
//   },
// ];
