const menuTypes = [
  {
    id: "itemmenu",
    value: "CRUD & Menu",
    description: "Access CRUD functionalities for managing entries.",
  },
  {
    id: "sub-menu",
    value: "Sub Menu",
    description: "Serves as a parent for child menu options.",
  },
  {
    id: "information-page",
    value: "Information Page",
    description: "Provides detailed information for the selected item.",
  },
  {
    id: "label",
    value: "Menu Label",
    description: "Categorizes menu items as group headers.",
  },
  {
    id: "custom-page",
    value: "Custom Page",
    description: "Interacts with personalized content.",
  },
];
const modelAttributes = [
  {
    type: "title",
    required: false,
    title: "Model Configuration",
    name: "modelConfig",
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Model Name",
    name: "modelName",
    default: "", // Default value set
    validation: "required", // Indicates that this field is required
    label: "Model Name",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "API Name",
    name: "apiName",
    default: "", // Default value set
    validation: "required", // Indicates that this field is required
    label: "API Name",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Type of Model",
    name: "typeofModel",
    default: "", // Default value set
    validation: "required", // Indicates that this field is required
    label: "Type of Model",
    required: true,
    view: true,
    add: true,
    update: true,
    options: ["standard", "custom", "dynamic"], // Sample options for the type of model
  },
  {
    type: "text",
    placeholder: "Short Name",
    name: "shortName",
    default: "", // Default value set
    label: "Short Name",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Description",
    name: "description",
    default: "", // Default value set
    label: "Description",
    required: false,
    view: true,
    add: true,
    update: true,
  },

  {
    type: "title",
    required: false,
    title: "Permissions",
    name: "permissions",
    add: true,
    update: true,
  },
  {
    type: "checkbox",
    label: "Allow Add Permission",
    name: "add",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow adding", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Edit Permission",
    name: "edit",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow editing", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Delete Permission",
    name: "delete",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow deletion", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Filter Permission",
    name: "filter",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow filtering", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Sort Permission",
    name: "sort",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow sorting", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Print Permission",
    name: "print",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow printing", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Export Permission",
    name: "export",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow exporting", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Search Permission",
    name: "search",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow searching", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Customization Permission",
    name: "customization",
    default: false,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Check to allow customization", // Placeholder for checkbox
  },
];
const projectAttributes = [
  {
    type: "title",
    required: false,
    title: "Project Configuration",
    name: "projectConfig",
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Project Title",
    name: "title",
    default: "",
    validation: "required", // Indicates that this field is required
    label: "Project Title",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    default: "",
    placeholder: "Project Description",
    name: "description",
    validation: "required", // Indicates that this field is required
    label: "Project Description",
    required: true,
    view: true,
    add: true,
    update: true,
  },

  {
    type: "title",
    required: false,
    title: "Database Configuration",
    name: "dbConfig",
    add: true,
    update: true,
  },
  {
    type: "text",
    default: "",
    placeholder: "Database Type",
    name: "dbType",
    validation: "required", // Indicates that this field is required
    label: "Database Type",
    required: true,
    view: true,
    add: true,
    update: true,
    options: ["mongodb", "postgresql", "mysql"], // Added options for database types
  },
  {
    type: "text",
    default: "",
    placeholder: "Username",
    name: "dbUsername", // Changed to dbUsername for consistency
    validation: "required", // Indicates that this field is required
    label: "Username",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "password",
    placeholder: "Password",
    name: "dbPassword", // Changed to dbPassword for consistency
    validation: "required", // Indicates that this field is required and has a minimum length
    label: "Password",
    default: "",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    default: "",
    placeholder: "Host",
    name: "dbHost",
    validation: "required", // Indicates that this field is required
    label: "Host",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "number",
    placeholder: "Port",
    name: "dbPort",
    validation: "required", // Indicates that this field is required
    label: "Port",
    required: true,
    view: true,
    add: true,
    update: true,
    default: 27017, // Default MongoDB port
  },
  {
    type: "text",
    default: "",
    placeholder: "Database Name",
    name: "dbName",
    validation: "required", // Indicates that this field is required
    label: "Database Name",
    required: true,
    view: true,
    add: true,
    update: true,
  },

  {
    type: "title",
    required: false,
    title: "Project Status",
    name: "projectStatus",
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Development Status",
    name: "developmentStatus",
    apiType: "JSON",
    selectApi: [
      { id: "discussion", value: "Discussion" },
      { id: "designing", value: "Designing" },
      { id: "developing", value: "Developing" },
      { id: "testing", value: "Testing" },
      { id: "deployment", value: "Deployment" },
      { id: "live", value: "Live" },
      { id: "proposal", value: "Proposal" },
      { id: "accepted", value: "Accepted" },
    ], // Valid values for development status
    validation: "required",
    label: "Development Status",
    required: true,
    customClass: "half",
    view: true,
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Project Status",
    name: "projectStatus",
    apiType: "JSON",
    selectApi: [
      { id: "inquiry", value: "Inquiry" },
      { id: "discussion", value: "Discussion" },
      { id: "proposal", value: "Proposal" },
      { id: "proposalAccepted", value: "Proposal Accepted" },
      { id: "declined", value: "Declined" },
      { id: "onDevelopment", value: "On Development" },
      { id: "onLive", value: "On Live" },
    ], // Valid values for project status
    validation: "required",
    label: "Project Status",
    required: true,
    view: true,
    add: true,
    update: true,
  },

  {
    type: "title",
    required: false,
    title: "Financial Information",
    name: "financialInfo",
    add: true,
    update: true,
  },
  {
    type: "number",
    placeholder: "Project Cost",
    name: "projectCost",
    validation: "required", // Indicates that this field is required
    label: "Project Cost",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "number",
    placeholder: "Annual Maintenance Cost (AMC)",
    name: "amc",
    validation: "", // Optional field
    label: "Annual Maintenance Cost (AMC)",
    required: false,
    view: true,
    add: true,
    update: true,
    default: 0, // Default value for AMC
  },
  {
    type: "title",
    required: false,
    title: "Documentation Links",
    name: "documentationLinks",
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Client",
    name: "client",
    showItem: "value",
    apiType: "API",
    selectApi: "clients/select",
    validation: "required",
    label: "Client",
    required: true,
    filter: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "multiSelect",
    placeholder: "Team Members",
    name: "teamMembers",
    // selectType: "card",
    showItem: "value",
    apiType: "API",
    selectApi: "members/select",
    validation: "required",
    label: "Team Members",
    required: true,
    view: true,
    add: true,
    update: true,
    tag: true,
  },
  {
    type: "text",
    placeholder: "Documentation URL",
    name: "documentationUrl",
    validation: "url", // Validating URL format
    label: "Documentation URL",
    default: "",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Repository Frontend URL",
    name: "repositoryFrontendUrl",
    default: "",
    validation: "required", // Indicates that this field is required
    label: "Repository Frontend URL",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Repository Backend URL",
    name: "repositoryBackendUrl",
    default: "",
    validation: "required", // Indicates that this field is required
    label: "Repository Backend URL",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Deployment URL",
    name: "deploymentUrl",
    default: "",
    validation: "url", // Optional field
    label: "Deployment URL",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "title",
    required: false,
    title: "Additional Information",
    name: "additionalInfo",
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Version",
    name: "version",
    label: "Version",
    required: false,
    view: true,
    add: true,
    update: true,
    default: "1.0.0", // Default version
  },
  {
    type: "textarea",
    default: "",
    placeholder: "Notes",
    name: "notes",
    validation: "", // Optional field
    label: "Notes",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    default: "",
    placeholder: "Tags",
    name: "tags",
    validation: "", // Optional field
    label: "Tags",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "title",
    required: false,
    title: "Technical Stack",
    name: "techStack",
    add: true,
    update: true,
  },
  {
    type: "mobilenumber",
    placeholder: "Phone Number",
    name: "clientPhoneNumber",
    countries: [
      {
        _id: "663761f21f9776f8c079e44d",
        title: "India",
        flag: "🇮🇳",
        phoneCode: 91,
        PhoneNumberLength: 10,
      },
    ],
    validation: "",
    default: "",
    tag: true,
    label: "Client Phone Number",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "multiSelect",
    placeholder: "Technology Stack",
    name: "techStack",
    apiType: "JSON",
    selectApi: [
      { id: "react", value: "React" },
      { id: "nodejs", value: "Node.js" },
      { id: "express", value: "Express" },
      { id: "mongodb", value: "MongoDB" },
      { id: "graphql", value: "GraphQL" },
      { id: "redux", value: "Redux" },
      { id: "typescript", value: "TypeScript" },
    ], // List of possible technologies
    validation: "required",
    label: "Technology Stack",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "image",
    placeholder: "BackgroundImageUrl",
    name: "logo",
    validation: "",
    default: "false",
    tag: true,
    label: "BackgroundImageUrl",
    required: true,
    view: true,
    add: true,
    update: true,
    multiple: true,
    maxFiles: 5,
  },
];
const attributeAttributes = [
  {
    type: "select",
    placeholder: "Type",
    name: "type",
    apiType: "JSON",
    selectApi: [
      { id: "reference", value: "Reference" },
      { id: "select", value: "Select" },
      { id: "multiSelect", value: "Multi Select" },
      { id: "text", value: "Text" },
      { id: "textarea", value: "Text Area" },
      { id: "image", value: "Image" },
      { id: "checkbox", value: "Check Box" },
      { id: "date", value: "Date" },
      { id: "number", value: "Number" },
      { id: "datetime", value: "Date Time" },
      { id: "email", value: "Email" },
      { id: "password", value: "Password" },
    ],
    validation: "required",
    label: "Type",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Label",
    name: "label",
    default: "", // Default value set
    label: "Label",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Placeholder",
    name: "placeholder",
    default: "", // Default value set
    label: "Placeholder",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "number",
    placeholder: "Sequence",
    name: "sequence",
    default: "", // Default value set
    label: "Sequence",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "checkbox",
    label: "Is Required",
    name: "required",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Is Required", // Placeholder for checkbox
  },
  {
    type: "text",
    placeholder: "Validation",
    name: "validation",
    default: "", // Default value set
    label: "Validation",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Api Type",
    name: "apiType",
    condition: {
      item: "type",
      if: ["select", "multiSelect"],
      then: "enabled",
      else: "disabled",
    },
    default: "",
    apiType: "JSON",
    selectApi: [
      { id: "API", value: "API" },
      { id: "JSON", value: "JSON" },
      { id: "CSV", value: "CSV" },
    ],
    validation: "",
    label: "Api Type",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "textarea",
    default: "",
    condition: {
      item: "type",
      if: ["select", "multiSelect"],
      then: "enabled",
      else: "disabled",
    },
    placeholder: "Options",
    name: "options",
    validation: "",
    label: "Options",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Reference",
    name: "reference",
    condition: {
      item: "type",
      if: "reference",
      then: "enabled",
      else: "disabled",
    },
    showItem: "value",
    apiType: "API",
    selectApi: "model/select",
    validation: "",
    label: "Reference",
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "checkbox",
    label: "Allow Add Permission",
    name: "add",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Add", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Edit Permission",
    name: "edit",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Edit", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow tag Permission",
    name: "tag",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Tag", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow show Permission",
    name: "show",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Show", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Print Permission",
    name: "print",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Print", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Export Permission",
    name: "export",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Export", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Search Permission",
    name: "search",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Search", // Placeholder for checkbox
  },
  {
    type: "checkbox",
    label: "Allow Customization Permission",
    name: "customization",
    default: true,
    required: false,
    view: true,
    add: true,
    update: true,
    placeholder: "Customization", // Placeholder for checkbox
  },
  {
    type: "select",
    placeholder: "Field Type",
    name: "fieldType",
    apiType: "JSON",
    selectApi: [
      { id: "String", value: "String" },
      { id: "Number", value: "Number" },
      { id: "Date", value: "Date" },
      { id: "Buffer", value: "Buffer" },
      { id: "Boolean", value: "Boolean" },
      { id: "Mixed", value: "Mixed" },
      { id: "ObjectId", value: "ObjectId" },
      { id: "Array", value: "Array" },
      { id: "Decimal128", value: "Decimal128" },
      { id: "Map", value: "Map" },
    ],
    validation: "",
    label: "Field Type",
    required: false,
    view: true,
    add: true,
    update: true,
  },
];
const permissionAttributes = [
  {
    type: "select",
    apiType: "API",
    selectApi: "user-type/select",
    placeholder: "Role",
    name: "role",
    validation: "",
    showItem: "role",
    tag: true,
    default: "",
    label: "Role",
    required: true,
    view: true,
    add: true,
    update: true,
    filter: false,
  },
  {
    type: "multiSelect",
    placeholder: "Actions",
    listView: true,
    name: "actions",
    validation: "",
    label: "Actions",
    tag: true,
    required: true,
    view: true,
    customClass: "list",
    add: true,
    update: true,
    apiType: "JSON",
    search: false,
    selectApi: [
      { value: "Add", id: "add" },
      { value: "Edit", id: "edit" },
      { value: "Delete", id: "delete" },
      { value: "View", id: "view" },
      { value: "Print", id: "print" },
      { value: "Export", id: "export" },
      { value: "Filter", id: "filter" },
      { value: "Search", id: "search" },
    ],
  },
];
const menuAttributes = [
  {
    type: "text",
    placeholder: "Title",
    name: "title",
    validation: "",
    default: "",
    label: "Title",
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Select Sub Menu Type",
    name: "subMenuType",
    validation: "",
    default: "",
    tag: true,
    label: "Sub Menu Type",
    showItem: "",
    required: true,
    view: true,
    filter: false,
    add: true,
    update: true,
    tags: [{ title: "", item: "description", collection: "" }],
    apiType: "JSON",
    selectApi: menuTypes,
  },
  {
    type: "text",
    placeholder: "Element Key",
    condition: {
      item: "subMenuType",
      if: "custom-page",
      then: "enabled",
      else: "disabled",
    },
    name: "element",
    validation: "",
    default: "",
    label: "Element Key",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "select",
    placeholder: "Model",
    name: "model",
    condition: {
      item: "subMenuType",
      if: "itemmenu",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    tag: true,
    collection: "model",
    label: "Model",
    showItem: "value",
    required: true,
    view: true,
    filter: false,
    add: true,
    update: true,
    apiType: "API",
    selectApi: "model/select",
  },
  {
    type: "number",
    placeholder: "Order",
    name: "order",
    validation: "",
    default: 0,
    label: "Order",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Icon",
    name: "icon",
    validation: "",
    default: "",
    label: "Icon",
    required: false,
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "checkbox",
    placeholder: "Is Active",
    name: "isActive",
    validation: "",
    default: true,
    label: "Is Active",
    tag: true,
    required: true,
    view: true,
    add: true,
    update: true,
  },
];
export { projectAttributes, modelAttributes, attributeAttributes, permissionAttributes, menuAttributes };
