import { COMPARE_TYPES } from "../../../../../core/functions/conditions";

export const attendanceDataAttributes = [
  {
    type: "select",
    footnote: "",
    placeholder: "Choose Ticket",
    name: "ticket",
    validation: "",
    label: "Select Ticket",
    showItem: "value",
    filterDefault: "all",
    value: "all",
    preFill: [
      {
        id: "all",
        value: "All",
      },
    ],
    required: false,
    view: false,
    filter: true,
    add: false,
    update: true,
    apiType: "API",
    selectApi: "ticket/select/all/Ticket",
    export: false,
  },
  {
    type: "text",
    placeholder: "Name",
    name: "firstName",
    validation: "",
    default: "",
    tag: true,
    label: "Name",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "datetime",
    placeholder: "Checkin Time",
    name: "attendanceDate",
    validation: "",
    default: "",
    tag: true,
    label: "Checkin Time",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "mobilenumber",
    placeholder: "Phone Number",
    name: "authenticationId",
    validation: "",
    default: "",
    tag: true,
    label: "Phone Number",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "email",
    placeholder: "Email ID",
    name: "emailId",
    validation: "",
    default: "",
    tag: true,
    label: "Email ID",
    required: true,
    view: true,
    add: false,
    update: false,
  },
  {
    type: "hidden",
    placeholder: "Status",
    name: "status",
    validation: "",
    default: "",
    tag: true,
    label: "Status",
    required: true,
    view: true,
    add: false,
    update: false,
    hide: true,
    statusLabel: {
      nextLine: false,
      size: "small",
      conditions: [
        {
          when: "status",
          condition: COMPARE_TYPES.IS_TRUE,
          compare: true,
          type: "boolean",
          label: "Checked In",
          icon: "checked",
          color: "mint",
        },
        {
          when: "status",
          condition: COMPARE_TYPES.IS_FALSE,
          compare: false,
          type: "boolean",
          label: "Pending",
          icon: "pending",
          color: "beige",
        },
      ],
    },
  },
];

export const attendanceActionsAttributes = [
  {
    element: "button",
    type: "callback",
    callback: (item, data, refreshView, slNo) => {
      // getApproved(data._id, refreshView, slNo, "approve");
    },
    itemTitle: {
      name: "user",
      type: "text",
      collection: "",
    },
    condition: {
      item: "attendance",
      if: false,
      then: true,
      else: false,
    },
    icon: "checked",
    color: "green",
    title: "Check In",
    params: {
      api: ``,
      parentReference: "",
      itemTitle: {
        name: "user",
        type: "text",
        collection: "",
      },
      shortName: "Check In",
      addPrivilege: true,
      delPrivilege: true,
      updatePrivilege: true,
      customClass: "medium",
    },
    actionType: "button",
  },
];
