export const settingsAttributes = [
  {
    type: "label",
    label: "Whatsapp Configuration",
    info: "Configure WhatsApp to send messages and notifications using the WhatsApp API.",
    name: "sm",
    group: "WhatsApp Configuration",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    group: "WhatsApp Configuration",
    update: true,
  },
  {
    type: "select",
    placeholder: "Choose WhatsApp Configuration",
    name: "defaultWhatsapp",
    validation: "",
    // tag: true,
    editable: true,
    label: "Choose WhatsApp Configuration",
    group: "WhatsApp Configuration",
    sublabel: "",
    showItem: "",
    required: false,
    customClass: "full",
    filter: false,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      {
        value: "EventHex Whatsapp",
        id: "EventHex Whatsapp",
        description: "Use the built-in EventHex WhatsApp integration.",
      },
      {
        value: "Custom Whatsapp",
        id: "Custom Whatsapp",
        description: "Set up your own WhatsApp configuration via API.",
      },
    ],
  },
  {
    type: "select",
    apiType: "CSV",
    placeholder: "Whatsapp Account Provider",
    name: "whatsappAccountProvider",
    condition: {
      item: "defaultWhatsapp",
      if: "Custom Whatsapp",
      then: "enabled",
      else: "disabled",
    },
    selectApi: "Dxing,Alerts Panel,Official API",
    validation: "",
    default: "",
    label: "Whatsapp Account Provider",
    group: "WhatsApp Configuration",
    tag: true,
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Whatsapp Url",
    name: "whatsappUrl",
    condition: {
      item: "defaultWhatsapp",
      if: "Custom Whatsapp",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Whatsapp Url",
    group: "WhatsApp Configuration",
    view: false,
    add: true,
    update: true,
  },
  {
    type: "password",
    placeholder: "Whatsapp Access Token",
    name: "whatsappAccessToken",
    condition: {
      item: "defaultWhatsapp",
      if: "Custom Whatsapp",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Whatsapp Access Token",
    tag: false,
    group: "WhatsApp Configuration",
    view: false,
    add: true,
    update: true,
  },
  {
    type: "password",
    placeholder: "Whatsapp Account",
    name: "whatsappAccount",
    condition: {
      item: "defaultWhatsapp",
      if: "Custom Whatsapp",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    group: "WhatsApp Configuration",
    label: "Whatsapp Account",
    tag: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Email Configuration",
    info: "Send emails seamlessly using your preferred SMTP server.",
    name: "sm",
    group: "Email Configuration",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Email Configuration",
  },
  {
    type: "select",
    placeholder: "Choose Email Configuration",
    name: "defaultEmail",
    validation: "",
    // tag: true,
    editable: true,
    label: "Choose Email Configuration",
    group: "Email Configuration",
    sublabel: "",
    showItem: "",
    required: false,
    customClass: "full",
    filter: false,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      {
        value: "EventHex Email",
        id: "EventHex Email",
        description: "Utilize the built-in EventHex email service for sending emails.",
      },
      {
        value: "Custom Email",
        id: "Custom Email",
        description: "Set up your own SMTP server for complete email control.",
      },
    ],
  },
  {
    type: "select",
    placeholder: "Provider",
    name: "smtpProvider",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    group: "Email Configuration",
    label: "Provider",
    onChange: (name, updateValue) => {
      if (updateValue[name] === "Google") {
        updateValue["smtpHost"] = "smtp.gmail.com";
        updateValue["smtpPort"] = "587";
      } else if (updateValue[name] === "Outlook") {
        updateValue["smtpHost"] = "smtp.office365.com";
        updateValue["smtpPort"] = "587";
      } else {
        updateValue["smtpHost"] = "";
        updateValue["smtpPort"] = "";
      }
      return updateValue;
    },
    selectApi: "Google,Outlook,Other",
    apiType: "CSV",
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "SMTP HOST",
    name: "smtpHost",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    group: "Email Configuration",
    label: "SMTP HOST",
    tag: true,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "SMTP PORT",
    name: "smtpPort",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    group: "Email Configuration",
    default: "",
    label: "SMTP PORT",
    tag: true,
    view: false,
    add: true,
    update: true,
  },
  {
    type: "password",
    placeholder: "SMTP USERNAME",
    name: "smtpUsername",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    group: "Email Configuration",
    validation: "",
    default: "",
    label: "SMTP USERNAME",
    tag: false,
    view: false,
    add: true,
    update: true,
  },
  {
    type: "password",
    placeholder: "SMTP PASSWORD",
    group: "Email Configuration",
    name: "smtpPassword",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "SMTP PASSWORD",
    tag: false,
    view: false,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "SMTP FROM EMAIL",
    group: "Email Configuration",
    name: "smtpFromEmail",
    condition: {
      item: "defaultEmail",
      if: "Custom Email",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "SMTP FROM EMAIL",
    footnote: "Example: Sender Name<example@eventhex.com>",
    tag: true,
    view: false,
    add: true,
    update: true,
  },
  {
    type: "label",
    label: "Payment Configuration",
    info: "Set up payment methods to seamlessly accept payments for tickets.",
    name: "sm",
    group: "Payment Configuration",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Payment Configuration",
  },
  // {
  //   type: "select",
  //   placeholder: "Currency",
  //   name: "currency",
  //   validation: "",
  //   default: "INR",
  //   label: "Currency",
  //   group: "Payment Configuration",
  //   selectApi: "INR,USD,AED",
  //   apiType: "CSV",
  //   tag: true,
  //   view: true,
  //   add: true,
  //   update: true,
  // },
  {
    type: "select",
    placeholder: "Payment Options",
    name: "defaultPayment",
    validation: "",
    // tag: true,
    editable: true,
    label: "Payment Options",
    group: "Payment Configuration",
    sublabel: "",
    showItem: "",
    required: false,
    customClass: "full",
    filter: false,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      {
        value: "EventHex Payment",
        id: "EventHex Payment",
        description: "Use the built-in EventHex payment gateway for fast, secure transactions.",
      },
      {
        value: "Custom Payment",
        id: "Custom Payment",
        description: "Integrate your own payment solution.",
      },
      {
        value: "Manual Payment",
        id: "Manual Payment",
        description: "Customer Pay using back account/UPI manually.",
      },
    ],
  },
  {
    type: "info",
    content: "2% + Payment Gateway Charges + Tax(if applicable)",
    group: "Payment Configuration",
    add: true,
    update: true,
    condition: {
      item: "defaultPayment",
      if: "EventHex Payment",
      then: "enabled",
      else: "disabled",
    },
  },
  {
    type: "select",
    placeholder: "Payment Gateway",
    name: "paymentGateway",
    condition: {
      item: "defaultPayment",
      if: "Custom Payment",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "Razorpay",
    tag: true,
    label: "Payment Gateway",
    showItem: "",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      { id: "stripe", value: "Stripe" },
      { id: "razorpay", value: "Razorpay" },
      { id: "tap", value: "TapPay" },
    ],
    group: "Payment Configuration",
  },
  {
    type: "password",
    placeholder: "Enter your payment gateway API key",
    name: "paymentGatewayKey",
    condition: {
      item: "defaultPayment",
      if: "Custom Payment",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Payment Gateway API Key",
    footnote: "Your public API key from the payment provider's dashboard. Keep this secure and don't share publicly. Example format: pk_test_1234567890abcdef",
    tag: false,
    view: false,
    add: true,
    group: "Payment Configuration",
    update: true,
  },
  {
    type: "password",
    placeholder: "Enter your payment gateway secret key",
    name: "paymentGatewaySecret",
    condition: {
      item: "defaultPayment",
      if: "Custom Payment",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Payment Gateway Secret Key",
    footnote: "Your private secret key used for secure transactions. This is confidential and should never be exposed publicly. Example format: sk_test_1234567890abcdef",
    tag: false,
    group: "Payment Configuration",
    view: false,
    add: true,
    update: true,
  },
  {
    type: "text",
    placeholder: "Payment Link",
    name: "upiId",
    condition: {
      item: "defaultPayment",
      if: "Manual Payment",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Payment Link",
    tag: false,
    view: false,
    add: true,
    group: "Payment Configuration",
    update: true,
  },
  {
    type: "textarea",
    placeholder: "Bank Account Details",
    name: "bankAccount",
    condition: {
      item: "defaultPayment",
      if: "Manual Payment",
      then: "enabled",
      else: "disabled",
    },
    validation: "",
    default: "",
    label: "Bank Account Details",
    tag: false,
    group: "Payment Configuration",
    view: false,
    add: true,
    update: true,
  },
];

export const instaRecapSettingAttributes = [
  {
    type: "label",
    label: "Enable Login",
    name: "sm",
    group: "Enable Logins",
    icon: "logins",
    add: true,
    update: true,
  },
  {
    type: "line",
    group: "Enable Logins",
    icon: "logins",
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Enable Login",
    name: "enableLogin",
    validation: "",
    default: true,
    tag: true,
    group: "Enable Logins",
    label: "Enable Login for Instarecap",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "logins",
  },
  {
    type: "label",
    label: "Enable Bookmark",
    name: "sm",
    group: "Enable Bookmarks",
    icon: "book-mark",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Enable Bookmarks",
    icon: "book-mark",
  },
  {
    type: "toggle",
    placeholder: "Enable Bookmark",
    name: "enableBookmark",
    validation: "",
    default: true,
    tag: true,
    group: "Enable Bookmarks",
    label: "Enable Bookmark for Instarecap",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "book-mark",
  },
  {
    type: "label",
    label: "Translation Languages",
    name: "sm",
    group: "Translation Languages",
    icon: "language",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Translation Languages",
    icon: "language",
  },
  {
    type: "toggle",
    placeholder: "Enable Translation",
    name: "enableTranslation",
    validation: "",
    default: true,
    tag: true,
    group: "Translation Languages",
    label: "Enable Translation for Instarecap",
    required: false,
    view: true,
    add: true,
    update: true,
    icon: "language",
  },
  {
    type: "multiSelect",
    placeholder: "Translation Languages",
    name: "translationLanguages",
    validation: "",
    group: "Translation Languages",
    label: "Translation Languages",
    sublabel: "",
    showItem: "",
    editable: true,
    tag: true,
    required: false,
    add: true,
    update: true,
    view: true,
    filter: false,
    condition: {
      item: "enableTranslation",
      if: true,
      then: "enabled",
      else: "disabled",
    },
    customClass: "full",
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      { value: "Afrikaans", id: "Afrikaans" },
      { value: "Albanian", id: "Albanian" },
      { value: "Amharic", id: "Amharic" },
      { value: "Arabic", id: "Arabic" },
      { value: "Armenian", id: "Armenian" },
      { value: "Assamese", id: "Assamese" },
      { value: "Aymara", id: "Aymara" },
      { value: "Azerbaijani", id: "Azerbaijani" },
      { value: "Bambara", id: "Bambara" },
      { value: "Basque", id: "Basque" },
      { value: "Belarusian", id: "Belarusian" },
      { value: "Bengali", id: "Bengali" },
      { value: "Bhojpuri", id: "Bhojpuri" },
      { value: "Bosnian", id: "Bosnian" },
      { value: "Bulgarian", id: "Bulgarian" },
      { value: "Catalan", id: "Catalan" },
      { value: "Cebuano", id: "Cebuano" },
      { value: "Chichewa", id: "Chichewa" },
      { value: "Chinese (Simplified)", id: "Chinese (Simplified)" },
      { value: "Chinese (Traditional)", id: "Chinese (Traditional)" },
      { value: "Corsican", id: "Corsican" },
      { value: "Croatian", id: "Croatian" },
      { value: "Czech", id: "Czech" },
      { value: "Danish", id: "Danish" },
      { value: "Dhivehi", id: "Dhivehi" },
      { value: "Dogri", id: "Dogri" },
      { value: "Dutch", id: "Dutch" },
      { value: "English", id: "English" },
      { value: "Esperanto", id: "Esperanto" },
      { value: "Estonian", id: "Estonian" },
      { value: "Ewe", id: "Ewe" },
      { value: "Filipino", id: "Filipino" },
      { value: "Finnish", id: "Finnish" },
      { value: "French", id: "French" },
      { value: "Frisian", id: "Frisian" },
      { value: "Galician", id: "Galician" },
      { value: "Georgian", id: "Georgian" },
      { value: "German", id: "German" },
      { value: "Greek", id: "Greek" },
      { value: "Guarani", id: "Guarani" },
      { value: "Gujarati", id: "Gujarati" },
      { value: "Haitian Creole", id: "Haitian Creole" },
      { value: "Hausa", id: "Hausa" },
      { value: "Hawaiian", id: "Hawaiian" },
      { value: "Hebrew", id: "Hebrew" },
      { value: "Hindi", id: "Hindi" },
      { value: "Hmong", id: "Hmong" },
      { value: "Hungarian", id: "Hungarian" },
      { value: "Icelandic", id: "Icelandic" },
      { value: "Igbo", id: "Igbo" },
      { value: "Ilocano", id: "Ilocano" },
      { value: "Indonesian", id: "Indonesian" },
      { value: "Irish", id: "Irish" },
      { value: "Italian", id: "Italian" },
      { value: "Japanese", id: "Japanese" },
      { value: "Javanese", id: "Javanese" },
      { value: "Kannada", id: "Kannada" },
      { value: "Kazakh", id: "Kazakh" },
      { value: "Khmer", id: "Khmer" },
      { value: "Kinyarwanda", id: "Kinyarwanda" },
      { value: "Konkani", id: "Konkani" },
      { value: "Korean", id: "Korean" },
      { value: "Krio", id: "Krio" },
      { value: "Kurdish (Kurmanji)", id: "Kurdish (Kurmanji)" },
      { value: "Kurdish (Sorani)", id: "Kurdish (Sorani)" },
      { value: "Kyrgyz", id: "Kyrgyz" },
      { value: "Lao", id: "Lao" },
      { value: "Latin", id: "Latin" },
      { value: "Latvian", id: "Latvian" },
      { value: "Lingala", id: "Lingala" },
      { value: "Lithuanian", id: "Lithuanian" },
      { value: "Luganda", id: "Luganda" },
      { value: "Luxembourgish", id: "Luxembourgish" },
      { value: "Macedonian", id: "Macedonian" },
      { value: "Maithili", id: "Maithili" },
      { value: "Malagasy", id: "Malagasy" },
      { value: "Malay", id: "Malay" },
      { value: "Malayalam", id: "Malayalam" },
      { value: "Maltese", id: "Maltese" },
      { value: "Maori", id: "Maori" },
      { value: "Marathi", id: "Marathi" },
      { value: "Meiteilon (Manipuri)", id: "Meiteilon (Manipuri)" },
      { value: "Mizo", id: "Mizo" },
      { value: "Mongolian", id: "Mongolian" },
      { value: "Myanmar (Burmese)", id: "Myanmar (Burmese)" },
      { value: "Nepali", id: "Nepali" },
      { value: "Norwegian", id: "Norwegian" },
      { value: "Odia (Oriya)", id: "Odia (Oriya)" },
      { value: "Oromo", id: "Oromo" },
      { value: "Pashto", id: "Pashto" },
      { value: "Persian", id: "Persian" },
      { value: "Polish", id: "Polish" },
      { value: "Portuguese", id: "Portuguese" },
      { value: "Punjabi", id: "Punjabi" },
      { value: "Quechua", id: "Quechua" },
      { value: "Romanian", id: "Romanian" },
      { value: "Russian", id: "Russian" },
      { value: "Samoan", id: "Samoan" },
      { value: "Sanskrit", id: "Sanskrit" },
      { value: "Scots Gaelic", id: "Scots Gaelic" },
      { value: "Sepedi", id: "Sepedi" },
      { value: "Serbian", id: "Serbian" },
      { value: "Sesotho", id: "Sesotho" },
      { value: "Shona", id: "Shona" },
      { value: "Sindhi", id: "Sindhi" },
      { value: "Sinhala", id: "Sinhala" },
      { value: "Slovak", id: "Slovak" },
      { value: "Slovenian", id: "Slovenian" },
      { value: "Somali", id: "Somali" },
      { value: "Spanish", id: "Spanish" },
      { value: "Sundanese", id: "Sundanese" },
      { value: "Swahili", id: "Swahili" },
      { value: "Swedish", id: "Swedish" },
      { value: "Tagalog", id: "Tagalog" },
      { value: "Tajik", id: "Tajik" },
      { value: "Tamil", id: "Tamil" },
      { value: "Tatar", id: "Tatar" },
      { value: "Telugu", id: "Telugu" },
      { value: "Thai", id: "Thai" },
      { value: "Tigrinya", id: "Tigrinya" },
      { value: "Tsonga", id: "Tsonga" },
      { value: "Turkish", id: "Turkish" },
      { value: "Turkmen", id: "Turkmen" },
      { value: "Twi", id: "Twi" },
      { value: "Ukrainian", id: "Ukrainian" },
      { value: "Urdu", id: "Urdu" },
      { value: "Uyghur", id: "Uyghur" },
      { value: "Uzbek", id: "Uzbek" },
      { value: "Vietnamese", id: "Vietnamese" },
      { value: "Welsh", id: "Welsh" },
      { value: "Xhosa", id: "Xhosa" },
      { value: "Yiddish", id: "Yiddish" },
      { value: "Yoruba", id: "Yoruba" },
      { value: "Zulu", id: "Zulu" },
    ],
  },
  {
    type: "label",
    label: "Profile Fields",
    info: "Manage your profile fields",
    name: "sm",
    group: "Profile Fields",
    icon: "profile-fields",
    add: true,
    update: true,
  },
  {
    type: "line",
    add: true,
    update: true,
    group: "Profile Fields",
    icon: "profile-fields",
  },
  {
    type: "toggle",
    placeholder: "Name",
    name: "name",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Name",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Whatsapp Number",
    name: "whatsappNumber",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Whatsapp Number",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Mobile Number",
    name: "mobileNumber",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Mobile Number",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Designation",
    name: "designation",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Designation",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Company",
    name: "company",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Company",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Gender",
    name: "gender",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Gender",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
  {
    type: "toggle",
    placeholder: "Bio",
    name: "bio",
    validation: "",
    default: true,
    tag: true,
    group: "Profile Fields",
    label: "Bio",
    required: false,
    view: true,
    filter: false,
    add: true,
    update: true,
  },
];

// export const websiteSettingsAttributes = [
//   {
//     type: "label",
//     label: "SEO Settings",
//     name: "sm",
//     icon: "app-setting",
//     group: "SEO Settings",
//     add: true,
//     update: true,
//   },
//   {
//     type: "line",
//     group: "SEO Settings",
//     icon: "app-setting",
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Meta Title",
//     name: "meta_title",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Meta Title",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//     customClass: "half",
//   },
//   {
//     type: "text",
//     placeholder: "Meta Description",
//     name: "meta_description",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Meta Description",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Meta Keywords",
//     name: "meta_keywords",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Meta Keywords",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Meta Robots",
//     name: "meta_robots",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Meta Robots",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Canonical URL",
//     name: "canonical_url",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Canonical URL",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "OG Title",
//     name: "og_title",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "OG Title",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "OG Description",
//     name: "og_description",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "OG Description",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "image",
//     placeholder: "OG Image",
//     name: "og_image",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "OG Image",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Twitter Card",
//     name: "twitter_card",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Twitter Card",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Twitter Title",
//     name: "twitter_title",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Twitter Title",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Twitter Description",
//     name: "twitter_description",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Twitter Description",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "image",
//     placeholder: "Twitter Image",
//     name: "twitter_image",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Twitter Image",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
//   {
//     type: "text",
//     placeholder: "Structured Data",
//     name: "structured_data",
//     validation: "",
//     default: true,
//     tag: true,
//     label: "Structured Data",
//     group: "SEO Settings",
//     required: false,
//     view: true,
//     add: true,
//     update: true,
//   },
// ];

// export const mobileModulesAttributes = [
//   // {
//   //   type: "multiSelect",
//   //   placeholder: "Mobile Modules",
//   //   name: "mobileModules",
//   //   validation: "",
//   //   tag: true,
//   //   editable: true,
//   //   label: "Mobile Modules",
//   //   group: "Mobile Module",
//   //   sublabel: "",
//   //   showItem: "",
//   //   required: false,
//   //   customClass: "full",
//   //   filter: false,
//   //   view: true,
//   //   add: true,
//   //   update: true,
//   //   apiType: "JSON",
//   //   selectType: "card",
//   //   selectApi: [
//   //     { value: "InstaSnap", id: "InstaSnap" },
//   //     { value: "Networking", id: "Networking" },
//   //     { value: "Meetings", id: "Meetings" },
//   //     { value: "Messaging", id: "Messaging" },
//   //     { value: "Speakers", id: "Speakers" },
//   //     { value: "Exhibitors", id: "Exhibitors" },
//   //     { value: "Sessions", id: "Sessions" },
//   //     { value: "Sponsors", id: "Sponsors" },
//   //     { value: "Feedback", id: "Feedback" },
//   //     { value: "Videos", id: "Videos" },
//   //     { value: "Ticket", id: "Ticket" },
//   //     { value: "AI Chat", id: "AI Chat" },
//   //   ],
//   // },
//   {
//     type: "multiSelect",
//     placeholder: "Core Modules",
//     name: "coreModules",
//     validation: "",
//     selectType: "card",
//     editable: true,
//     customClass: "full",
//     label: "Core Modules",
//     showItem: "",
//     required: true,
//     filter: false,
//     view: true,
//     add: true,
//     // group: "Modules",
//     update: true,
//     apiType: "API",
//     selectApi: "event-module/select",
//   },
//   {
//     type: "multiSelect",
//     placeholder: "Addons",
//     name: "addons",
//     validation: "",
//     selectType: "card",
//     editable: true,
//     label: "Addons",
//     showItem: "",
//     required: true,
//     filter: false,
//     view: true,
//     add: true,
//     // group: "Modules",
//     update: true,
//     customClass: "full",
//     apiType: "API",
//     selectApi: "add-on/select",
//   },
// ];

export const mobileModulesAttributes = [
  {
    type: "multiSelect",
    placeholder: "Mobile Modules",
    name: "mobileModules",
    validation: "",
    tag: true,
    editable: true,
    label: "",
    group: "Mobile Module",
    sublabel: "",
    showItem: "",
    required: false,
    customClass: "full",
    filter: false,
    view: true,
    add: true,
    update: true,
    apiType: "JSON",
    selectType: "card",
    selectApi: [
      { id: "InstaSnap", value: "InstaSnap", description: "Add an InstaSnap feature to your event for attendees to take photos and videos and share them with each other", icon: "insta-snap" },
      { id: "InstaRecap", value: "InstaRecap", description: "Add an InstaRecap feature to your event for attendees to take photos and videos and share them with each other", icon: "insta-recap" },
      { id: "Networking", value: "Networking", description: "Add a networking feature to your event for attendees to connect with each other before or after the event", icon: "networking" },
      { id: "Meetings", value: "Meetings", description: "Add a meetings feature to your event for attendees to connect with each other before or after the event", icon: "networking" },
      { id: "Messaging", value: "Messaging", description: "Add a messaging feature to your event for attendees to communicate with each other", icon: "message" },
      { id: "Speakers", value: "Speakers", description: "Add and manage speakers or guests for your sessions`", icon: "speakers" },
      { id: "Exhibitors", value: "Exhibitors", description: "Add exhibitors to your event for attendees to learn more about", icon: "exhibitor" },
      { id: "Sessions", value: "Sessions", description: "Manage event sessions(enable if applicable)", icon: "session" },
      { id: "Sponsors", value: "Sponsors", description: "Add exhibitors and sponsors to your event for attendees to learn more about", icon: "exhibitor" },
      { id: "Feedback", value: "Feedback", description: "Add a feedback feature to your event for attendees to provide feedback", icon: "feedback" },
      { id: "Videos", value: "Videos", description: "Add a videos feature to your event for attendees to watch videos", icon: "video" },
      { id: "Ticket", value: "Ticket", description: "Add a ticket feature to your event for attendees to purchase tickets", icon: "ticket" },
      { id: "AI Chat", value: "AI Chat", description: "Add an AI chat feature to your event for attendees to communicate with each other", icon: "message" },
    ],
  },
  // {
  //   type: "multiSelect",
  //   placeholder: "Core Modules",
  //   name: "mobileModules",
  //   validation: "",
  //   selectType: "card",
  //   editable: true,
  //   customClass: "full",
  //   label: "Core Modules",
  //   showItem: "",
  //   required: false,
  //   filter: false,
  //   view: true,
  //   add: true,
  //   group: "Modules",
  //   update: true,
  //   apiType: "JSON",
  //   selectApi: [
  //     { id: "InstaSnap", value: "InstaSnap", description: "Add an InstaSnap feature to your event for attendees to take photos and videos and share them with each other", icon: "insta-snap" },
  //     { id: "InstaRecap", value: "InstaRecap", description: "Add an InstaRecap feature to your event for attendees to take photos and videos and share them with each other", icon: "insta-recap" },
  //     { id: "Sessions", value: "Sessions", description: "Manage event sessions(enable if applicable)", icon: "session" },
  //     { id: "Speakers", value: "Speakers", description: "Add and manage speakers or guests for your sessions`", icon: "speakers" },
  //     { id: "Networking", value: "Networking", description: "Add a networking feature to your event for attendees to connect with each other before or after the event", icon: "networking" },
  //     { id: "Attendee Chat", value: "Attendee Chat", description: "Add an attendee chat feature to your event for attendees to communicate with each other", icon: "message" },
  //     { id: "Location", value: "Location", description: "Add a location feature to your event for attendees to find the event", icon: "location" },
  //     { id: "Exhibitors & Sponsors", value: "Exhibitors & Sponsors", description: "Add exhibitors and sponsors to your event for attendees to learn more about", icon: "exhibitor" },
  //   ],
  // },
];
