import { getCountries } from "../countries";

export const sponsorsAttributes = (eventCountries = []) => {
  return [
    {
      type: "text",
      placeholder: "Brand Name",
      name: "title",
      validation: "",
      default: "",
      tag: true,
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
      icon: "brand",
      image: { field: "logo", collection: "" },
      description: { type: "text", field: "emailId", collection: "" },
    },
    {
      type: "mobilenumber",
      placeholder: "Contact Number",
      name: "authenticationId",
      validation: "",
      default: "",
      tag: false,
      label: "Contact Number",
      required: false,
      view: true,
      add: true,
      update: true,
      countries: getCountries(eventCountries),
      icon: "number",
    },
    {
      type: "text",
      placeholder: "Email",
      name: "emailId",
      validation: "",
      default: "",
      tag: false,
      label: "Email",
      required: false,
      view: true,
      add: true,
      update: true,
      icon: "email",
    },
    {
      type: "text",
      placeholder: "Enter brand Website",
      name: "website",
      validation: "",
      default: "",
      label: "Website URL",
      tag: true,
      required: false,
      view: true,
      add: true,
      update: true,
      icon: "link",
    },
    {
      type: "textarea",
      placeholder: "A brief description about the sponsor ...",
      name: "description",
      validation: "",
      default: "",
      label: "Description",
      sublabel: "Optional",
      tag: false,
      required: false,
      view: true,
      add: true,
      update: true,
      icon: "description",
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "sponsor-category/select",
      placeholder: "Basic",
      name: "sponsorCategory",
      validation: "",
      showItem: "sponsorCategory",
      icon: "sponsors",
      addNew: {
        attributes: [
          {
            type: "text",
            placeholder: "Basic",
            name: "sponsorCategory",
            validation: "",
            default: "",
            tag: true,
            label: "Sponsor Category",
            required: true,
            view: true,
            add: true,
            update: true,
            icon: "sponsors",
          },
          {
            type: "line",
            add: true,
            update: true,
          },
          {
            type: "textarea",
            placeholder: "A brief description about the category ...",
            name: "description",
            validation: "",
            default: "",
            label: "Description",
            sublabel: "Optional",
            tag: false,
            required: false,
            view: true,
            add: true,
            update: true,
          },
          {
            type: "number",
            placeholder: "Order Id",
            name: "orderId",
            validation: "",
            default: "",
            label: "Order Id",
            required: true,
            view: true,
            add: true,
            update: true,
            icon: "orders",
          },
          {
            type: "line",
            add: true,
            update: true,
          },
        ],
        api: "sponsor-category",
        submitButtonText: "Create",
      },
      default: "",
      tag: true,
      label: "Sponsor Category",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: true,
    },
    {
      type: "image",
      placeholder: "Logo",
      name: "logo",
      validation: "",
      default: "false",
      tag: false,
      label: "Logo",
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ];
};

export const sponsorCategoryAttributes = [
  {
    type: "text",
    placeholder: "Basic",
    name: "sponsorCategory",
    validation: "",
    default: "",
    tag: true,
    label: "Sponsor Category",
    required: true,
    view: true,
    add: true,
    update: true,
    description: { type: "text", field: "description", collection: "" },
    icon: "sponsor-category",
  },
  {
    type: "textarea",
    placeholder: "A brief description about the category ...",
    name: "description",
    validation: "",
    default: "",
    label: "Description",
    sublabel: "Optional",
    tag: false,
    required: false,
    view: true,
    add: true,
    update: true,
  },
  {
    type: "number",
    placeholder: "Order Id",
    name: "orderId",
    validation: "",
    default: "",
    label: "Order Id",
    required: true,
    view: true,
    add: true,
    update: true,
    icon: "orders",
  },
];
