import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const BadgeCertificate = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Badge Certificate - goCampus Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "text",
      placeholder: "Name",
      name: "name",
      showItem: "",
      validation: "",
      default: "",
      tag: false,
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Orientation",
      name: "orientation",
      validation: "",
      default: "",
      label: "Orientation",
      showItem: "Orientation",
      tag: true,
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Portrait,Landscape",
    },
    {
      type: "select",
      placeholder: "Type",
      name: "type",
      validation: "",
      default: "",
      label: "Type",
      showItem: "Type",
      tag: true,
      required: true,
      view: true,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Badge,Certificate",
    },
    {
      type: "number",
      placeholder: "Length",
      name: "length",
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Length",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Width",
      name: "width",
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Width",
      required: true,
      view: true,
      add: true,
      update: true,
    },
  ]);

  const [badgeCertificateField] = useState([
    // {
    //   type: "select",
    //   apiType: "API",
    //   selectApi: "badge-certificate/select",
    //   placeholder: "Badge",
    //   name: "badge",
    //   validation: "",
    //   showItem: "name",
    //   default: "",
    //   label: "Badge",
    //   required: false,
    //   view: true,
    //   add: true,
    //   update: true,
    //   filter: false,
    // },
    {
      type: "select",
      placeholder: "Layer Type",
      name: "layerType",
      validation: "",
      default: "",
      label: "Layer Type",
      showItem: "Layer Type",
      tag: true,
      required: false,
      view: true,
      filter: false,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "BackgroundImage,BackgroundGradient,Text,Image,Qr",
    },
    {
      type: "text",
      placeholder: "Height",
      name: "height",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Height",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Width",
      name: "width",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Width",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Sequence",
      name: "sequence",
      showItem: "",
      validation: "",
      default: "0",
      tag: true,
      label: "Sequence",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Sample",
      name: "sample",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Sample",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Text Colour",
      name: "textColour",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Text Colour",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "BackgroundImageUrl",
      name: "source",
      validation: "",
      condition: {
        item: "layerType",
        if: "BackgroundImage",
        then: "enabled",
        else: "disabled",
      },
      default: "false",
      tag: true,
      label: "BackgroundImageUrl",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Position",
      name: "position",
      condition: {
        item: "layerType",
        if: "BackgroundImage",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Position",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "cover,contain",
    },
    {
      type: "select",
      placeholder: "Source",
      name: "source",
      condition: {
        item: "layerType",
        if: "BackgroundGradient",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Source",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "ColourPicker",
    },
    {
      type: "select",
      apiType: "API",
      placeholder: "Source",
      name: "source",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      params: [{ name: "ticket" }],
      validation: "",
      default: "",
      tag: true,
      label: "Source",
      required: false,
      view: true,
      add: true,
      update: true,
      selectApi: "ticket-form-data/select",
    },
    {
      type: "text",
      placeholder: "Font",
      name: "font",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Font",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Font Size",
      name: "fontSize",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Font Size",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Font Style",
      name: "fontStyle",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "Normal",
      tag: true,
      label: "Font Style",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Bold,Italic,Underline,Normal",
    },
    {
      type: "select",
      placeholder: "Alignment",
      name: "textAlignment",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Alignment",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Left,Right,Justify,Center",
    },
    {
      type: "text",
      placeholder: "Top",
      name: "top",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Top",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Bottom",
      name: "bottom",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Bottom",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Right",
      name: "right",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Right",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Left",
      name: "left",
      condition: {
        item: "layerType",
        if: "Text",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "auto",
      tag: true,
      label: "Left",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Alignment",
      name: "textAlignment",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Alignment",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Left,Right,Justify,Center",
    },
    {
      type: "text",
      placeholder: "Top",
      name: "top",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Top",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Bottom",
      name: "bottom",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Bottom",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Left",
      name: "left",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "auto",
      tag: true,
      label: "Left",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Right",
      name: "right",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Right",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Position",
      name: "position",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Position",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "cover,contain",
    },
    {
      type: "select",
      placeholder: "Shape",
      name: "shape",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Shape",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Round,Square,Curved",
    },
    {
      type: "image",
      placeholder: "Image Url",
      name: "source",
      validation: "",
      condition: {
        item: "layerType",
        if: "Image",
        then: "enabled",
        else: "disabled",
      },
      default: "false",
      tag: true,
      label: "Image Url",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Alignment",
      name: "textAlignment",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Alignment",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Left,Right,Justify,Center",
    },
    {
      type: "text",
      placeholder: "Top",
      name: "top",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Top",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Bottom",
      name: "bottom",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Bottom",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Left",
      name: "left",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "auto",
      tag: true,
      label: "Left",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Right",
      name: "right",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "10px",
      tag: true,
      label: "Right",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Source",
      name: "source",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Source",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "FieldName",
    },
    {
      type: "text",
      placeholder: "Prefix",
      name: "prefix",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Prefix",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Suffix",
      name: "suffix",
      condition: {
        item: "layerType",
        if: "Qr",
        then: "enabled",
        else: "disabled",
      },
      showItem: "",
      validation: "",
      default: "",
      tag: true,
      label: "Suffix",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ]);

  const [actions] = useState([
    {
      element: "button",
      type: "subList",
      id: "badgeCertificateField",
      title: "Badge Certificate Fields",
      icon: "badgeCertificateField",
      attributes: badgeCertificateField,
      params: {
        api: `badge-certificate-field`,
        parentReference: "badge",
        itemTitle: {
          name: "layerType",
          type: "text",
          collection: "",
        },
        shortName: "Badge Certificate Fields",
        addPrivilege: true,
        delPrivilege: true,
        updatePrivilege: true,
        customClass: "medium",
      },
    },
  ]);
  return (
    <Container className="noshadow">
      <ListTable
        actions={actions}
        api={`badge-certificate`}
        itemTitle={{ name: "name", type: "text", collection: "" }}
        shortName={`Badge Certificate`}
        formMode={`single`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
// exporting the page with parent container layout..
export default Layout(BadgeCertificate);
