import { attributeAttributes, menuAttributes, modelAttributes, permissionAttributes } from "../attributes/project";

export const projectActions = [
  {
    element: "button",
    type: "subList",
    id: "Schemas",
    title: "Schemas",
    icon: "Schemas",
    attributes: modelAttributes,
    params: {
      api: `model`,
      parentReference: "project",
      icon: "model",
      itemTitle: { name: "shortName", type: "text", collection: "" },
      shortName: "Schema",
      addPrivilege: true,
      delPrivilege: true,
      updatePrivilege: true,
      customClass: "medium",
      formMode: `double`,
      popupMode: "full-page",
      popupMenu: "vertical-menu",
      actions: [
        {
          element: "button",
          type: "subList",
          id: "attributes",
          itemTitle: "label",
          title: "Attributes",
          icon: "attributes",
          attributes: attributeAttributes,
          params: {
            api: `attribute`,
            parentReference: "model",
            icon: "ticket-form-data",
            itemTitle: {
              name: "label",
              type: "text",
              collection: "",
            },
            shortName: "Attributes",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
            formMode: `double`,
            additionalButtons: [
              {
                label: "JSON Upload",
                onClick: (item) => {
                  console.log("OnClick json", item);
                //   setJsonUpload(item);
                },
                icon: "add",
              },
            ],
          },
        },
        {
          element: "button",
          type: "subList",
          id: "Sort",
          itemTitle: "Sort",
          title: "Sort",
          icon: "sort",
          attributes: attributeAttributes,
          params: {
            preFilter: { type: "sort" },
            api: `sort-filter`,
            parentReference: "model",
            icon: "filter",
            shortName: "Sort",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
            formMode: `double`,
          },
        },
        {
          element: "button",
          type: "subList",
          id: "Filter",
          itemTitle: "Filter",
          title: "Filter",
          icon: "filter",
          attributes: attributeAttributes,
          params: {
            preFilter: { type: "filter" },
            api: `sort-filter`,
            parentReference: "model",
            icon: "filter",
            shortName: "Filter",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
            formMode: `double`,
          },
        },
        {
          element: "button",
          type: "subList",
          id: "env",
          itemTitle: "key",
          title: "Environmental Variables",
          icon: "env",
          attributes: attributeAttributes,
          params: {
            preenv: { type: "env" },
            api: `env`,
            parentReference: "model",
            icon: "env",
            shortName: "Environmental Variables",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
            formMode: `double`,
          },
        },
      ],
    },
  },
  {
    element: "button",
    type: "subList",
    id: "Menus",
    title: "Menus",
    icon: "Menus",
    attributes: menuAttributes,
    params: {
      api: `menu-item`,
      parentReference: "project",
      preFilter: { parentId: null },
      icon: "model",
      itemTitle: { name: "title", type: "text", collection: "" },
      shortName: "Menus",
      addPrivilege: true,
      delPrivilege: true,
      updatePrivilege: true,
      customClass: "medium",
      formMode: `double`,
      popupMode: "full-page",
      popupMenu: "vertical-menu",
      additionalButtons: [
        {
          label: "View Menu",
          onClick: (item) => {
            console.log("OnClick", item);
            // setOpenItemData(item);
          },
          icon: "menu",
        },
      ],
      actions: [
        {
          element: "button",
          type: "subList",
          id: "permission",
          title: "Permissions",
          attributes: permissionAttributes,
          params: {
            api: `permission`,
            parentReference: "menuItem",
            itemTitle: {
              name: "role",
              type: "text",
              collection: "role",
            },
            shortName: "Permissions",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
          },
        },
        {
          element: "button",
          type: "subList",
          id: "sub-menu",
          title: "Sub Menu",
          attributes: menuAttributes,
          params: {
            api: `menu-item`,
            parentReference: "parentId",
            itemTitle: { name: "title", type: "text", collection: "" },
            shortName: "Sub Menu",
            addPrivilege: true,
            delPrivilege: true,
            updatePrivilege: true,
            customClass: "medium",
            formMode: `double`,
            actions: [
              {
                element: "button",
                type: "subList",
                id: "permission",
                title: "Permissions",
                attributes: permissionAttributes,
                params: {
                  api: `permission`,
                  parentReference: "menuItem",
                  itemTitle: {
                    name: "role",
                    type: "text",
                    collection: "role",
                  },
                  shortName: "Permissions",
                  addPrivilege: true,
                  delPrivilege: true,
                  updatePrivilege: true,
                  customClass: "medium",
                },
              },
              {
                element: "button",
                type: "subList",
                id: "sub-menu",
                title: "Sub Menu",
                attributes: menuAttributes,
                params: {
                  api: `menu-item`,
                  parentReference: "parentId",
                  itemTitle: { name: "title", type: "text", collection: "" },
                  shortName: "Sub Menu",
                  addPrivilege: true,
                  delPrivilege: true,
                  updatePrivilege: true,
                  customClass: "medium",
                  formMode: `double`,
                  actions: [
                    {
                      element: "button",
                      type: "subList",
                      id: "permission",
                      title: "Permissions",
                      attributes: permissionAttributes,
                      params: {
                        api: `permission`,
                        parentReference: "menuItem",
                        itemTitle: {
                          name: "role",
                          type: "text",
                          collection: "role",
                        },
                        shortName: "Permissions",
                        addPrivilege: true,
                        delPrivilege: true,
                        updatePrivilege: true,
                        customClass: "medium",
                      },
                    },
                    {
                      element: "button",
                      type: "subList",
                      id: "sub-menu",
                      title: "Sub Menu",
                      attributes: menuAttributes,
                      params: {
                        api: `menu-item`,
                        parentReference: "parentId",
                        itemTitle: {
                          name: "title",
                          type: "text",
                          collection: "",
                        },
                        shortName: "Sub Menu",
                        addPrivilege: true,
                        delPrivilege: true,
                        updatePrivilege: true,
                        customClass: "medium",
                        formMode: `double`,
                        actions: [
                          {
                            element: "button",
                            type: "subList",
                            id: "permission",
                            title: "Permissions",
                            attributes: permissionAttributes,
                            params: {
                              api: `permission`,
                              parentReference: "menuItem",
                              itemTitle: {
                                name: "role",
                                type: "text",
                                collection: "role",
                              },
                              shortName: "Permissions",
                              addPrivilege: true,
                              delPrivilege: true,
                              updatePrivilege: true,
                              customClass: "medium",
                            },
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
    },
  },
];
