import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";

//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const WebsiteSettings = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Website Settings - goCampus Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "title",
      required: false,
      title: " Display Modules",
      name: "displayModules",
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Speaker",
      name: "speakers",
      validation: "",
      default: null,
      tag: true,
      label: "Speakers",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Sessions",
      name: "sessions",
      validation: "",
      default: null,
      tag: false,
      label: "Sessions",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Sponsors",
      name: "sponsors",
      validation: "",
      default: null,
      tag: false,
      label: "Sponsors",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Location",
      name: "location",
      validation: "",
      default: null,
      tag: false,
      label: "Location",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Attendees",
      name: "attendees",
      validation: "",
      default: null,
      tag: false,
      label: "Attendees",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Agenda",
      name: "agenda",
      validation: "",
      default: null,
      tag: false,
      label: "Agenda",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Gallery",
      name: "gallery",
      validation: "",
      default: null,
      tag: false,
      label: "Gallery",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "FAQs",
      name: "faqs",
      validation: "",
      default: null,
      tag: false,
      label: "FAQs",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Contact",
      name: "contact",
      validation: "",
      default: null,
      tag: false,
      label: "Contact",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Feedback",
      name: "feedback",
      validation: "",
      default: null,
      tag: false,
      label: "Feedback",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      required: false,
      title: "Appearance & Event Info",
      name: "appearanceEventInfo",
      add: true,
      update: true,
    },
    {
      type: "color",
      placeholder: "Primary Color",
      name: "primary_color",
      validation: "",
      default: "#000000",
      tag: false,
      label: "Primary Color",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "color",
      placeholder: "Secondary Color",
      name: "secondary_color",
      validation: "",
      default: "#ffffff",
      tag: false,
      label: "Secondary Color",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "Logo",
      name: "logo",
      validation: "",
      default: null,
      tag: false,
      label: "Logo",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "Favicon",
      name: "favicon",
      validation: "",
      default: null,
      tag: false,
      label: "Favicon",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Theme",
      name: "theme",
      validation: "",
      default: null,
      tag: false,
      label: "Theme",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "JSON",
      selectApi: [
        { id: "light", value: "Light" },
        { id: "dark", value: "Dark" },
        { id: "custom", value: "Custom" },
      ],
    },
    {
      type: "select",
      placeholder: "Language",
      name: "language",
      validation: "",
      default: null,
      tag: false,
      label: "Language",
      required: false,
      view: true,
      add: true,
      update: true,
      apiType: "JSON",
      selectApi: [{ id: "en", value: "English" }],
    },
    {
      type: "date",
      placeholder: "Date Format",
      name: "date_format",
      validation: "",
      default: null,
      tag: false,
      label: "Date Format",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "time",
      placeholder: "Time Format",
      name: "time_format",
      validation: "",
      default: "",
      tag: false,
      label: "Time Format",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Footer Text",
      name: "footer_text",
      validation: "",
      default: null,
      tag: false,
      label: "Footer Text",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      required: false,
      title: "Event Mode & Links",
      name: "eventModeLinks",
      add: true,
      update: true,
    },
    {
      type: "checkbox",
      placeholder: "Meeting Link Visible Before Registration",
      name: "meeting_link_visible_before_registration",
      validation: "",
      default: null,
      tag: false,
      label: "Meeting Link Visible Before Registration",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      required: false,
      title: "Customization",
      name: "customization",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Analytics Code",
      name: "analytics_code",
      validation: "",
      default: null,
      tag: false,
      label: "Analytics Code",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      required: false,
      title: "SEO Settings",
      name: "seoSettings",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Meta Title",
      name: "meta_title",
      validation: "",
      default: null,
      tag: true,
      label: "Meta Title",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Meta Description",
      name: "meta_description",
      validation: "",
      default: null,
      tag: false,
      label: "Meta Description",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Meta Keywords",
      name: "meta_keywords",
      validation: "",
      default: null,
      tag: true,
      label: "Meta Keywords",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Meta Robots",
      name: "meta_robots",
      validation: "",
      default: null,
      tag: true,
      label: "Meta Robots",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Canonical URL",
      name: "canonical_url",
      validation: "",
      default: null,
      tag: false,
      label: "Canonical URL",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "OG Title",
      name: "og_title",
      validation: "",
      default: null,
      tag: true,
      label: "OG Title",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "OG Description",
      name: "og_description",
      validation: "",
      default: null,
      tag: false,
      label: "OG Description",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "OG Image",
      name: "og_image",
      validation: "",
      default: null,
      tag: false,
      label: "OG Image",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Twitter Card",
      name: "twitter_card",
      validation: "",
      default: null,
      tag: false,
      label: "Twitter Card",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Twitter Title",
      name: "twitter_title",
      validation: "",
      default: null,
      tag: true,
      label: "Twitter Title",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Twitter Description",
      name: "twitter_description",
      validation: "",
      default: null,
      tag: false,
      label: "Twitter Description",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "image",
      placeholder: "Twitter Image",
      name: "twitter_image",
      validation: "",
      default: null,
      tag: false,
      label: "Twitter Image",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Structured Data",
      name: "structured_data",
      validation: "",
      default: null,
      tag: false,
      label: "Structured Data",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`website-settings`}
        // itemTitle={`label`}
        itemTitle={{
          name: "displayModules",
          type: "text",
          collection: "",
        }}
        shortName={`WebsiteSettings`}
        formMode={`single`}
        attributes={attributes}
        {...props}
      ></ListTable>
    </Container>
  );
};

export default Layout(WebsiteSettings);
