import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const SubscriptionPlan = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Subscription Plan - EventHex Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "text",
      placeholder: "Title",
      name: "title",
      validation: "",
      default: "",
      label: "Title",
      tag: true,
      required: true,
      view: true,
      add: true,
      update: true,
    },
    // {
    //   type: "select",
    //   apiType: "API",
    //   selectApi: "subscription-plan-price/select",
    //   placeholder: "Default Pricing Plan",
    //   name: "defaultPricing",
    //   validation: "",
    //   showItem: "value",
    //   default: "",
    //   tag: true,
    //   label: "Default Pricing Plan",
    //   required: false,
    //   view: true,
    //   add: true,
    //   update: true,
    //   params: [{ name: "_id" }],
    //   filter: false,
    // },
    {
      type: "text",
      placeholder: "Default Pricing Plan",
      name: "defaultPricing",
      validation: "",
      default: "",
      label: "Default Pricing Plan",
      tag: true,
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "textarea",
      placeholder: "Description",
      name: "description",
      validation: "",
      default: "",
      tag: true,
      label: "Description",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "toggle",
      placeholder: "Active",
      name: "active",
      validation: "",
      default: true,
      tag: false,
      label: "Active",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "htmleditor",
      placeholder: "Features",
      name: "features",
      validation: "",
      default: "",
      tag: false,
      label: "Features",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Default Payment Method",
      name: "defaultPaymentMethod",
      showItem: "",
      validation: "",
      default: "stripe",
      tag: true,
      label: "Default Payment Method",
      required: true,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "stripe,razorpay",
    },
    {
      type: "number",
      placeholder: "Number of InstaRecap",
      name: "noOfInstaRecap",
      validation: "",
      default: 0,
      tag: false,
      label: "Number of InstaRecap",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Number of InstaSnap",
      name: "noInstaSnap",
      validation: "",
      default: 0,
      tag: false,
      label: "Number of InstaSnap",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Number of EventHex",
      name: "noEventHex",
      validation: "",
      default: 0,
      tag: false,
      label: "Number of EventHex",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "InstaSnap Storage Per Event",
      name: "instaSnapStoragePerEvent",
      validation: "",
      default: 0,
      tag: false,
      label: "InstaSnap Storage Per Event",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Attendees Per Event",
      name: "attendeesPerEvent",
      validation: "",
      default: 0,
      tag: false,
      label: "Attendees Per Event",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "InstaRecap Per Event",
      name: "instaRecapPerEvent",
      validation: "",
      default: 0,
      tag: false,
      label: "InstaRecap Per Event",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ]);

  // const [subscriptionPlanModule] = useState([
  //   {
  //     type: "select",
  //     apiType: "API",
  //     selectApi: "subscription-plan/select",
  //     placeholder: "Subscription Plan",
  //     name: "subscriptionPlan",
  //     validation: "",
  //     showItem: "value",
  //     default: "",
  //     tag: true,
  //     label: "Subscription Plan",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //     filter: false,
  //   },
  //   {
  //     type: "multiSelect",
  //     apiType: "API",
  //     selectApi: "event-module/select",
  //     placeholder: "Module",
  //     name: "module",
  //     validation: "",
  //     showItem: "value",
  //     default: "",
  //     tag: true,
  //     label: "Module",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //     filter: false,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Count",
  //     name: "count",
  //     validation: "",
  //     default: 1,
  //     tag: true,
  //     label: "Count",
  //     required: true,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  // ]);

  // const [subscriptionCoupon] = useState([
  //   {
  //     type: "text",
  //     placeholder: "Code",
  //     name: "code",
  //     validation: "",
  //     default: "",
  //     label: "Code",
  //     tag: true,
  //     required: true,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "select",
  //     placeholder: "Type",
  //     name: "type",
  //     showItem: "",
  //     validation: "",
  //     default: "Fixed",
  //     tag: true,
  //     label: "Type",
  //     required: true,
  //     view: true,
  //     add: true,
  //     update: true,
  //     apiType: "CSV",
  //     selectApi: "Percentage,Fixed",
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Value",
  //     name: "price",
  //     validation: "",
  //     default: null,
  //     tag: true,
  //     label: "Value",
  //     required: true,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Min Purchase",
  //     name: "minPurchase",
  //     validation: "",
  //     default: 0,
  //     tag: false,
  //     label: "Min Purchase",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Max Discount",
  //     name: "maxDiscount",
  //     validation: "",
  //     default: "",
  //     tag: false,
  //     label: "Max Discount",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "date",
  //     placeholder: "Start Date",
  //     name: "startDate",
  //     validation: "",
  //     default: "",
  //     tag: false,
  //     label: "Start Date",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "date",
  //     placeholder: "End Date",
  //     name: "endDate",
  //     validation: "",
  //     default: "",
  //     tag: false,
  //     label: "End Date",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Usage Limit",
  //     name: "usageLimit",
  //     validation: "",
  //     default: 1,
  //     tag: false,
  //     label: "Usage Limit",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Used Count",
  //     name: "usedCount",
  //     validation: "",
  //     default: 0,
  //     tag: false,
  //     label: "Used Count",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "toggle",
  //     placeholder: "Is Active",
  //     name: "isActive",
  //     validation: "",
  //     default: true,
  //     tag: true,
  //     label: "Is Active",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "select",
  //     apiType: "API",
  //     selectApi: "subscription-plan/select",
  //     placeholder: "Subscription Plan",
  //     name: "package",
  //     validation: "",
  //     showItem: "value",
  //     default: "",
  //     tag: false,
  //     label: "Subscription Plan",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //     filter: false,
  //   },
  // ]);

  // const [pricing] = useState([
  //   {
  //     type: "select",
  //     apiType: "API",
  //     selectApi: "country/select",
  //     placeholder: "Country",
  //     name: "country",
  //     validation: "",
  //     showItem: "value",
  //     default: "",
  //     label: "Country",
  //     required: true,
  //     view: true,
  //     tag: true,
  //     add: true,
  //     update: true,
  //     filter: false,
  //   },
  //   {
  //     type: "select",
  //     apiType: "API",
  //     selectApi: "currency/select",
  //     placeholder: "Currency",
  //     name: "currency",
  //     validation: "",
  //     showItem: "value",
  //     default: "",
  //     label: "Currency",
  //     required: true,
  //     view: true,
  //     tag: true,
  //     add: true,
  //     update: true,
  //     filter: false,
  //   },
  //   {
  //     type: "text",
  //     placeholder: "Razorpay Plan ID",
  //     name: "razorpayId",
  //     validation: "",
  //     default: "",
  //     label: "Razorpay Plan ID",
  //     tag: true,
  //     required: true,
  //     view: true,
  //     add: false,
  //     update: false,
  //   },
  //   {
  //     type: "text",
  //     placeholder: "Stripe Plan ID",
  //     name: "stripeId",
  //     validation: "",
  //     default: "",
  //     label: "Stripe Plan ID",
  //     tag: true,
  //     required: true,
  //     view: true,
  //     add: false,
  //     update: false,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Price",
  //     name: "price",
  //     validation: "",
  //     default: "false",
  //     tag: true,
  //     label: "Price",
  //     required: true,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   {
  //     type: "number",
  //     placeholder: "Offer Price",
  //     name: "offerPrice",
  //     validation: "",
  //     default: "false",
  //     tag: true,
  //     label: "Offer Price",
  //     required: false,
  //     view: true,
  //     add: true,
  //     update: true,
  //   },
  //   // {
  //   //   type: "multiSelect",
  //   //   apiType: "API",
  //   //   selectApi: "subscription-plan/select",
  //   //   placeholder: "Subscription Plan",
  //   //   name: "subscriptionPlan",
  //   //   validation: "",
  //   //   showItem: "value",
  //   //   default: "",
  //   //   tag: false,
  //   //   label: "Subscription Plan",
  //   //   required: false,
  //   //   view: false,
  //   //   add: false,
  //   //   update: false,
  //   //   filter: false,
  //   // },
  // ]);

  // const [actions] = useState([
  //   {
  //     element: "button",
  //     type: "subList",
  //     id: "subscription-plan-module",
  //     title: "Module",
  //     icon: "core-module",
  //     attributes: subscriptionPlanModule,
  //     params: {
  //       api: `subscription-plan-module`,
  //       parentReference: "",
  //       itemTitle: {
  //         name: "value",
  //         type: "text",
  //         collection: "subscriptionPlan",
  //       },
  //       shortName: "Module",
  //       addPrivilege: true,
  //       delPrivilege: true,
  //       updatePrivilege: true,
  //       customClass: "medium",
  //       viewMode: "table",
  //     },
  //   },
  //   {
  //     element: "button",
  //     type: "subList",
  //     id: "subscription-coupon",
  //     title: "Coupon",
  //     icon: "subscription-coupon",
  //     attributes: subscriptionCoupon,
  //     params: {
  //       api: `subscription-coupon`,
  //       parentReference: "",
  //       itemTitle: {
  //         name: "code",
  //         type: "text",
  //         collection: "",
  //       },
  //       shortName: "Coupon",
  //       addPrivilege: true,
  //       delPrivilege: true,
  //       updatePrivilege: true,
  //       customClass: "medium",
  //       viewMode: "table",
  //     },
  //   },
  //   {
  //     element: "button",
  //     type: "subList",
  //     id: "price",
  //     title: "Pricing",
  //     icon: "price",
  //     attributes: pricing,
  //     params: {
  //       api: `subscription-plan-price`,
  //       parentReference: "subscriptionPlan",
  //       itemTitle: {
  //         name: "title",
  //         type: "text",
  //         collection: "country",
  //       },
  //       shortName: "Pricing",
  //       addPrivilege: true,
  //       delPrivilege: true,
  //       updatePrivilege: true,
  //       customClass: "medium",
  //       viewMode: "table",
  //     },
  //   },
  // ]);

  return (
    <Container className="noshadow">
      <ListTable
        // actions={actions}
        api={`subscription-plan`}
        itemTitle={{ name: "title", type: "text", collection: "" }}
        shortName={`Subscription Plan`}
        formMode={`single`}
        viewMode={`table`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
// exporting the page with parent container layout..
export default Layout(SubscriptionPlan);
