import React, { useEffect, useState } from "react";
import Layout from "../../../core/layout";
import ListTable from "../../../core/list/list";
import { Container } from "../../../core/layout/styels";
//src/components/styles/page/index.js
//if you want to write custom style wirte in above file
const SubscribedFranchise = (props) => {
  //to update the page title
  useEffect(() => {
    document.title = `Subscriptions - EventHex Portal`;
  }, []);

  const [attributes] = useState([
    {
      type: "text",
      placeholder: "Name",
      name: "name",
      validation: "",
      default: "",
      tag: true,
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Email",
      name: "email",
      validation: "",
      default: "",
      tag: false,
      label: "Email",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Phone",
      name: "phone",
      validation: "",
      default: "",
      tag: false,
      label: "Phone",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "subscription-plan/select",
      placeholder: "Subscription Plan",
      name: "activeSubscriptionPlan",
      validation: "",
      showItem: "value",
      default: "",
      tag: true,
      label: "Subscription Plan",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "franchise/select",
      placeholder: "Franchise",
      name: "franchise",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Franchise",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "multiSelect",
      apiType: "API",
      selectApi: "subscription-coupon/select",
      placeholder: "Coupon Codes Applied",
      name: "couponCodesApplied",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Coupon Codes Applied",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "date",
      placeholder: "Subscription Start Date",
      name: "subscriptionStartDate",
      validation: "",
      default: "",
      tag: false,
      label: "Subscription Start Date",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "date",
      placeholder: "Next Billing Date",
      name: "nextBillingDate",
      validation: "",
      default: "",
      tag: false,
      label: "Next Billing Date",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      placeholder: "Payment Status",
      name: "paymentStatus",
      showItem: "",
      validation: "",
      default: "Active",
      tag: true,
      label: "Payment Status",
      required: true,
      view: true,
      add: true,
      update: true,
      apiType: "CSV",
      selectApi: "Active,Pending,Cancelled",
    },
    {
      type: "toggle",
      placeholder: "Is Active",
      name: "isActive",
      validation: "",
      default: true,
      tag: true,
      label: "Is Active",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "event-module/select",
      placeholder: "Module",
      name: "module",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Module",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
  ]);

  const [subscribedFranchiseModule] = useState([
    {
      type: "select",
      apiType: "API",
      selectApi: "subscription-plan/select",
      placeholder: "Subscription Plan",
      name: "subscriptionPlan",
      validation: "",
      showItem: "value",
      default: "",
      tag: true,
      label: "Subscription Plan",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "multiSelect",
      apiType: "API",
      selectApi: "event-module/select",
      placeholder: "Module",
      name: "module",
      validation: "",
      showItem: "value",
      default: "",
      tag: true,
      label: "Module",
      required: true,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "number",
      placeholder: "Count",
      name: "count",
      validation: "",
      default: 1,
      tag: true,
      label: "Count",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "select",
      apiType: "API",
      selectApi: "franchise/select",
      placeholder: "Franchise",
      name: "franchise",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Franchise",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
  ]);

  const [billingAddress] = useState([
    {
      type: "select",
      apiType: "API",
      selectApi: "franchise/select",
      placeholder: "Franchise",
      name: "franchise",
      validation: "",
      showItem: "value",
      default: "",
      tag: false,
      label: "Franchise",
      required: false,
      view: true,
      add: true,
      update: true,
      filter: false,
    },
    {
      type: "title",
      title: "Address Details",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Address Line 1",
      name: "addressLine1",
      validation: "",
      default: "",
      tag: false,
      label: "Address Line 1",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Address Line 2",
      name: "addressLine2",
      validation: "",
      default: "",
      tag: false,
      label: "Address Line 2",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "City",
      name: "city",
      validation: "",
      default: "",
      tag: false,
      label: "City",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "State",
      name: "state",
      validation: "",
      default: "",
      tag: false,
      label: "State",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Country",
      name: "country",
      validation: "",
      default: "",
      tag: false,
      label: "Country",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Postal Code",
      name: "postalCode",
      validation: "",
      default: "",
      tag: false,
      label: "Postal Code",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      title: "Billing Contact Information",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Name",
      name: "contactPersonfirstName",
      validation: "",
      default: "",
      tag: true,
      label: "Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Last Name",
      name: "contactPersonlastName",
      validation: "",
      default: "",
      tag: false,
      label: "Last Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Email",
      name: "contactPersonemail",
      validation: "",
      default: "",
      tag: true,
      label: "Email",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "number",
      placeholder: "Phone",
      name: "contactPersonphone",
      validation: "",
      default: "",
      tag: false,
      label: "Phone",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Designation",
      name: "contactPersondesignation",
      validation: "",
      default: "",
      tag: false,
      label: "Designation",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "title",
      title: "Billing Details",
      name: "info",
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Company Name",
      name: "companyName",
      validation: "",
      default: "",
      tag: true,
      label: "Company Name",
      required: true,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "Tax ID",
      name: "taxId",
      validation: "trim",
      default: "",
      tag: false,
      label: "Tax ID",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "VAT Number",
      name: "vatNumber",
      validation: "trim",
      default: "",
      tag: false,
      label: "VAT Number",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "text",
      placeholder: "GST Number",
      name: "gstNumber",
      validation: "trim",
      default: "",
      tag: false,
      label: "GST Number",
      required: false,
      view: true,
      add: true,
      update: true,
    },
    {
      type: "toggle",
      placeholder: "Is Default",
      name: "isDefault",
      validation: "",
      default: false,
      tag: true,
      label: "Is Default",
      required: false,
      view: true,
      add: true,
      update: true,
    },
  ]);

  const [actions] = useState([
    {
      element: "button",
      type: "subList",
      id: "subscribed-franchise-module",
      title: "Subscribed Franchise Module",
      icon: "mobile-modules",
      attributes: subscribedFranchiseModule,
      params: {
        api: `subscribed-franchise-module`,
        parentReference: "",
        itemTitle: {
          name: "value",
          type: "text",
          collection: "subscriptionPlan",
        },
        shortName: "Subscribed Franchise Module",
        addPrivilege: true,
        delPrivilege: true,
        updatePrivilege: true,
        customClass: "medium",
        viewMode: "table",
      },
    },
    {
      element: "button",
      type: "subList",
      id: "billing-address",
      title: "Billing Address",
      icon: "billing-address",
      attributes: billingAddress,
      params: {
        api: `billing-address`,
        parentReference: "",
        itemTitle: {
          name: "contactPersonfirstName",
          type: "text",
          collection: "",
        },
        shortName: "Billing Address",
        addPrivilege: true,
        delPrivilege: true,
        updatePrivilege: true,
        customClass: "medium",
        viewMode: "table",
      },
    },
  ]);

  return (
    <Container className="noshadow">
      <ListTable
        actions={actions}
        api={`subscribed-franchise`}
        itemTitle={{ name: "name", type: "text", collection: "" }}
        shortName={`Subscriptions`}
        // parentReference={"event"}
        formMode={`single`}
        viewMode={`table`}
        {...props}
        attributes={attributes}
      ></ListTable>
    </Container>
  );
};
// exporting the page with parent container layout..
export default Layout(SubscribedFranchise);
